//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cts_supervision_DeviceSearchResultVew
    {
        public string DeviceCode { get; set; }
        public string DeviceTypeName { get; set; }
        public string CustomerName { get; set; }
        public string StatusName { get; set; }
        public Nullable<short> Status { get; set; }
        public int DeviceType { get; set; }
    }
}
