//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IN_SearchVehicleLane
    {
        public string TicketID { get; set; }
        public System.DateTime CheckDate { get; set; }
        public string LaneName { get; set; }
        public string ShiftName { get; set; }
        public int TicketName { get; set; }
        public string UserName { get; set; }
        public string RecogPlateNumber { get; set; }
        public string PostCheck { get; set; }
        public Nullable<short> PrecheckStatus { get; set; }
        public Nullable<short> SupervisionStatus { get; set; }
    }
}
