//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ListVehicleInOut
    {
        public System.Guid CheckID { get; set; }
        public System.DateTime InDate { get; set; }
        public string InVehicleTypeName { get; set; }
        public string InRecogPlateNumber { get; set; }
        public string InEmployee { get; set; }
        public Nullable<System.DateTime> OutDate { get; set; }
        public string OutVehicleTypeName { get; set; }
        public string OutRecogPlateNumber { get; set; }
        public string OutEmployee { get; set; }
    }
}
