//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Out_CheckSmartCardMonth6
    {
        public string ReceiptNo { get; set; }
        public string SmartCardID { get; set; }
        public System.DateTime CheckDate { get; set; }
        public Nullable<int> ChargeAmount { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public Nullable<int> LaneID { get; set; }
        public Nullable<int> StationID { get; set; }
    }
}
