#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HPE")]
	public partial class QLHPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAC_PPCWhiteList(AC_PPCWhiteList instance);
    partial void UpdateAC_PPCWhiteList(AC_PPCWhiteList instance);
    partial void DeleteAC_PPCWhiteList(AC_PPCWhiteList instance);
    partial void InsertIN_CheckPrepaidCard(IN_CheckPrepaidCard instance);
    partial void UpdateIN_CheckPrepaidCard(IN_CheckPrepaidCard instance);
    partial void DeleteIN_CheckPrepaidCard(IN_CheckPrepaidCard instance);
    partial void InsertOUT_CheckPrepaidCard(OUT_CheckPrepaidCard instance);
    partial void UpdateOUT_CheckPrepaidCard(OUT_CheckPrepaidCard instance);
    partial void DeleteOUT_CheckPrepaidCard(OUT_CheckPrepaidCard instance);
    partial void InsertOUT_CheckSmartCard(OUT_CheckSmartCard instance);
    partial void UpdateOUT_CheckSmartCard(OUT_CheckSmartCard instance);
    partial void DeleteOUT_CheckSmartCard(OUT_CheckSmartCard instance);
    partial void InsertIN_CheckSmartCard(IN_CheckSmartCard instance);
    partial void UpdateIN_CheckSmartCard(IN_CheckSmartCard instance);
    partial void DeleteIN_CheckSmartCard(IN_CheckSmartCard instance);
    #endregion
		
		public QLHPDataContext() : 
				base(global::TollTicketManagement.Properties.Settings.Default.HPEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<AC_PPCWhiteList> AC_PPCWhiteLists
		{
			get
			{
				return this.GetTable<AC_PPCWhiteList>();
			}
		}
		
		public System.Data.Linq.Table<AC_TollWhiteList> AC_TollWhiteLists
		{
			get
			{
				return this.GetTable<AC_TollWhiteList>();
			}
		}
		
		public System.Data.Linq.Table<IN_CheckPrepaidCard> IN_CheckPrepaidCards
		{
			get
			{
				return this.GetTable<IN_CheckPrepaidCard>();
			}
		}
		
		public System.Data.Linq.Table<OUT_CheckPrepaidCard> OUT_CheckPrepaidCards
		{
			get
			{
				return this.GetTable<OUT_CheckPrepaidCard>();
			}
		}
		
		public System.Data.Linq.Table<OUT_CheckSmartCard> OUT_CheckSmartCards
		{
			get
			{
				return this.GetTable<OUT_CheckSmartCard>();
			}
		}
		
		public System.Data.Linq.Table<IN_CheckSmartCard> IN_CheckSmartCards
		{
			get
			{
				return this.GetTable<IN_CheckSmartCard>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AC_PPCWhiteList")]
	public partial class AC_PPCWhiteList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _CardID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private string _FormatID;
		
		private System.Nullable<int> _StationIDIn;
		
		private System.Nullable<int> _LaneIDIn;
		
		private System.Nullable<System.DateTime> _LastCheckDateIn;
		
		private System.Nullable<int> _StationIDOut;
		
		private System.Nullable<int> _LaneIDOut;
		
		private System.Nullable<System.DateTime> _LastCheckDateOut;
		
		private System.Nullable<int> _RouteID;
		
		private System.Nullable<int> _Hour;
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<bool> _IsUsed;
		
		private string _Note;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCardIDChanging(string value);
    partial void OnCardIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnFormatIDChanging(string value);
    partial void OnFormatIDChanged();
    partial void OnStationIDInChanging(System.Nullable<int> value);
    partial void OnStationIDInChanged();
    partial void OnLaneIDInChanging(System.Nullable<int> value);
    partial void OnLaneIDInChanged();
    partial void OnLastCheckDateInChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckDateInChanged();
    partial void OnStationIDOutChanging(System.Nullable<int> value);
    partial void OnStationIDOutChanged();
    partial void OnLaneIDOutChanging(System.Nullable<int> value);
    partial void OnLaneIDOutChanged();
    partial void OnLastCheckDateOutChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckDateOutChanged();
    partial void OnRouteIDChanging(System.Nullable<int> value);
    partial void OnRouteIDChanged();
    partial void OnHourChanging(System.Nullable<int> value);
    partial void OnHourChanged();
    partial void OnDayChanging(System.Nullable<int> value);
    partial void OnDayChanged();
    partial void OnMonthChanging(System.Nullable<int> value);
    partial void OnMonthChanged();
    partial void OnYearChanging(System.Nullable<int> value);
    partial void OnYearChanged();
    partial void OnIsUsedChanging(System.Nullable<bool> value);
    partial void OnIsUsedChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public AC_PPCWhiteList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CardID
		{
			get
			{
				return this._CardID;
			}
			set
			{
				if ((this._CardID != value))
				{
					this.OnCardIDChanging(value);
					this.SendPropertyChanging();
					this._CardID = value;
					this.SendPropertyChanged("CardID");
					this.OnCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatID", DbType="VarChar(20)")]
		public string FormatID
		{
			get
			{
				return this._FormatID;
			}
			set
			{
				if ((this._FormatID != value))
				{
					this.OnFormatIDChanging(value);
					this.SendPropertyChanging();
					this._FormatID = value;
					this.SendPropertyChanged("FormatID");
					this.OnFormatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDIn", DbType="Int")]
		public System.Nullable<int> StationIDIn
		{
			get
			{
				return this._StationIDIn;
			}
			set
			{
				if ((this._StationIDIn != value))
				{
					this.OnStationIDInChanging(value);
					this.SendPropertyChanging();
					this._StationIDIn = value;
					this.SendPropertyChanged("StationIDIn");
					this.OnStationIDInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDIn", DbType="Int")]
		public System.Nullable<int> LaneIDIn
		{
			get
			{
				return this._LaneIDIn;
			}
			set
			{
				if ((this._LaneIDIn != value))
				{
					this.OnLaneIDInChanging(value);
					this.SendPropertyChanging();
					this._LaneIDIn = value;
					this.SendPropertyChanged("LaneIDIn");
					this.OnLaneIDInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateIn
		{
			get
			{
				return this._LastCheckDateIn;
			}
			set
			{
				if ((this._LastCheckDateIn != value))
				{
					this.OnLastCheckDateInChanging(value);
					this.SendPropertyChanging();
					this._LastCheckDateIn = value;
					this.SendPropertyChanged("LastCheckDateIn");
					this.OnLastCheckDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDOut", DbType="Int")]
		public System.Nullable<int> StationIDOut
		{
			get
			{
				return this._StationIDOut;
			}
			set
			{
				if ((this._StationIDOut != value))
				{
					this.OnStationIDOutChanging(value);
					this.SendPropertyChanging();
					this._StationIDOut = value;
					this.SendPropertyChanged("StationIDOut");
					this.OnStationIDOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDOut", DbType="Int")]
		public System.Nullable<int> LaneIDOut
		{
			get
			{
				return this._LaneIDOut;
			}
			set
			{
				if ((this._LaneIDOut != value))
				{
					this.OnLaneIDOutChanging(value);
					this.SendPropertyChanging();
					this._LaneIDOut = value;
					this.SendPropertyChanged("LaneIDOut");
					this.OnLaneIDOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateOut
		{
			get
			{
				return this._LastCheckDateOut;
			}
			set
			{
				if ((this._LastCheckDateOut != value))
				{
					this.OnLastCheckDateOutChanging(value);
					this.SendPropertyChanging();
					this._LastCheckDateOut = value;
					this.SendPropertyChanged("LastCheckDateOut");
					this.OnLastCheckDateOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="Int")]
		public System.Nullable<int> RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="Int")]
		public System.Nullable<int> Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this.OnHourChanging(value);
					this.SendPropertyChanging();
					this._Hour = value;
					this.SendPropertyChanged("Hour");
					this.OnHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUsed", DbType="Bit")]
		public System.Nullable<bool> IsUsed
		{
			get
			{
				return this._IsUsed;
			}
			set
			{
				if ((this._IsUsed != value))
				{
					this.OnIsUsedChanging(value);
					this.SendPropertyChanging();
					this._IsUsed = value;
					this.SendPropertyChanged("IsUsed");
					this.OnIsUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AC_TollWhiteList")]
	public partial class AC_TollWhiteList
	{
		
		private System.Guid _ID;
		
		private string _CardID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private string _FormatID;
		
		private System.Nullable<int> _StationIDIn;
		
		private System.Nullable<int> _LaneIDIn;
		
		private System.Nullable<System.DateTime> _LastCheckDateIn;
		
		private System.Nullable<int> _StationIDOut;
		
		private System.Nullable<int> _LaneIDOut;
		
		private System.Nullable<System.DateTime> _LastCheckDateOut;
		
		private System.Nullable<int> _RouteID;
		
		private System.Nullable<int> _Hour;
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<bool> _IsUsed;
		
		private string _Note;
		
		public AC_TollWhiteList()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardID", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string CardID
		{
			get
			{
				return this._CardID;
			}
			set
			{
				if ((this._CardID != value))
				{
					this._CardID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this._VehicleTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatID", DbType="VarChar(20)")]
		public string FormatID
		{
			get
			{
				return this._FormatID;
			}
			set
			{
				if ((this._FormatID != value))
				{
					this._FormatID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDIn", DbType="Int")]
		public System.Nullable<int> StationIDIn
		{
			get
			{
				return this._StationIDIn;
			}
			set
			{
				if ((this._StationIDIn != value))
				{
					this._StationIDIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDIn", DbType="Int")]
		public System.Nullable<int> LaneIDIn
		{
			get
			{
				return this._LaneIDIn;
			}
			set
			{
				if ((this._LaneIDIn != value))
				{
					this._LaneIDIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateIn
		{
			get
			{
				return this._LastCheckDateIn;
			}
			set
			{
				if ((this._LastCheckDateIn != value))
				{
					this._LastCheckDateIn = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDOut", DbType="Int")]
		public System.Nullable<int> StationIDOut
		{
			get
			{
				return this._StationIDOut;
			}
			set
			{
				if ((this._StationIDOut != value))
				{
					this._StationIDOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDOut", DbType="Int")]
		public System.Nullable<int> LaneIDOut
		{
			get
			{
				return this._LaneIDOut;
			}
			set
			{
				if ((this._LaneIDOut != value))
				{
					this._LaneIDOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateOut
		{
			get
			{
				return this._LastCheckDateOut;
			}
			set
			{
				if ((this._LastCheckDateOut != value))
				{
					this._LastCheckDateOut = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="Int")]
		public System.Nullable<int> RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this._RouteID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="Int")]
		public System.Nullable<int> Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this._Hour = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this._Day = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this._Month = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this._Year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUsed", DbType="Bit")]
		public System.Nullable<bool> IsUsed
		{
			get
			{
				return this._IsUsed;
			}
			set
			{
				if ((this._IsUsed != value))
				{
					this._IsUsed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this._Note = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IN_CheckPrepaidCard")]
	public partial class IN_CheckPrepaidCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _InCheckPrePaidCardID;
		
		private string _TransactionID;
		
		private string _SmartCardID;
		
		private System.DateTime _CheckDate;
		
		private System.Nullable<int> _TicketTypeID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<int> _ShiftID;
		
		private System.Nullable<int> _LaneID;
		
		private System.Nullable<int> _StationID;
		
		private string _ImageID;
		
		private string _RecogPlateNumber;
		
		private System.Nullable<short> _RecogResultType;
		
		private System.Nullable<short> _TransactionStatus;
		
		private System.Nullable<short> _PrecheckStatus;
		
		private System.Nullable<short> _PreSupervisionStatus;
		
		private System.Nullable<short> _SupervisionStatus;
		
		private System.Nullable<int> _ErrorID;
		
		private System.Nullable<System.Guid> _WIMID;
		
		private string _Note;
		
		private System.Nullable<bool> _IsVehicleInfoManual;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInCheckPrePaidCardIDChanging(System.Guid value);
    partial void OnInCheckPrePaidCardIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnSmartCardIDChanging(string value);
    partial void OnSmartCardIDChanged();
    partial void OnCheckDateChanging(System.DateTime value);
    partial void OnCheckDateChanged();
    partial void OnTicketTypeIDChanging(System.Nullable<int> value);
    partial void OnTicketTypeIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnShiftIDChanging(System.Nullable<int> value);
    partial void OnShiftIDChanged();
    partial void OnLaneIDChanging(System.Nullable<int> value);
    partial void OnLaneIDChanged();
    partial void OnStationIDChanging(System.Nullable<int> value);
    partial void OnStationIDChanged();
    partial void OnImageIDChanging(string value);
    partial void OnImageIDChanged();
    partial void OnRecogPlateNumberChanging(string value);
    partial void OnRecogPlateNumberChanged();
    partial void OnRecogResultTypeChanging(System.Nullable<short> value);
    partial void OnRecogResultTypeChanged();
    partial void OnTransactionStatusChanging(System.Nullable<short> value);
    partial void OnTransactionStatusChanged();
    partial void OnPrecheckStatusChanging(System.Nullable<short> value);
    partial void OnPrecheckStatusChanged();
    partial void OnPreSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnPreSupervisionStatusChanged();
    partial void OnSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnSupervisionStatusChanged();
    partial void OnErrorIDChanging(System.Nullable<int> value);
    partial void OnErrorIDChanged();
    partial void OnWIMIDChanging(System.Nullable<System.Guid> value);
    partial void OnWIMIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnIsVehicleInfoManualChanging(System.Nullable<bool> value);
    partial void OnIsVehicleInfoManualChanged();
    #endregion
		
		public IN_CheckPrepaidCard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InCheckPrePaidCardID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid InCheckPrePaidCardID
		{
			get
			{
				return this._InCheckPrePaidCardID;
			}
			set
			{
				if ((this._InCheckPrePaidCardID != value))
				{
					this.OnInCheckPrePaidCardIDChanging(value);
					this.SendPropertyChanging();
					this._InCheckPrePaidCardID = value;
					this.SendPropertyChanged("InCheckPrePaidCardID");
					this.OnInCheckPrePaidCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmartCardID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SmartCardID
		{
			get
			{
				return this._SmartCardID;
			}
			set
			{
				if ((this._SmartCardID != value))
				{
					this.OnSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._SmartCardID = value;
					this.SendPropertyChanged("SmartCardID");
					this.OnSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckDate", DbType="DateTime NOT NULL")]
		public System.DateTime CheckDate
		{
			get
			{
				return this._CheckDate;
			}
			set
			{
				if ((this._CheckDate != value))
				{
					this.OnCheckDateChanging(value);
					this.SendPropertyChanging();
					this._CheckDate = value;
					this.SendPropertyChanged("CheckDate");
					this.OnCheckDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketTypeID", DbType="Int")]
		public System.Nullable<int> TicketTypeID
		{
			get
			{
				return this._TicketTypeID;
			}
			set
			{
				if ((this._TicketTypeID != value))
				{
					this.OnTicketTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TicketTypeID = value;
					this.SendPropertyChanged("TicketTypeID");
					this.OnTicketTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="Int")]
		public System.Nullable<int> ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this.OnShiftIDChanging(value);
					this.SendPropertyChanging();
					this._ShiftID = value;
					this.SendPropertyChanged("ShiftID");
					this.OnShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneID", DbType="Int")]
		public System.Nullable<int> LaneID
		{
			get
			{
				return this._LaneID;
			}
			set
			{
				if ((this._LaneID != value))
				{
					this.OnLaneIDChanging(value);
					this.SendPropertyChanging();
					this._LaneID = value;
					this.SendPropertyChanged("LaneID");
					this.OnLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="Int")]
		public System.Nullable<int> StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", DbType="NVarChar(50)")]
		public string ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogPlateNumber", DbType="NVarChar(15)")]
		public string RecogPlateNumber
		{
			get
			{
				return this._RecogPlateNumber;
			}
			set
			{
				if ((this._RecogPlateNumber != value))
				{
					this.OnRecogPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._RecogPlateNumber = value;
					this.SendPropertyChanged("RecogPlateNumber");
					this.OnRecogPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogResultType", DbType="SmallInt")]
		public System.Nullable<short> RecogResultType
		{
			get
			{
				return this._RecogResultType;
			}
			set
			{
				if ((this._RecogResultType != value))
				{
					this.OnRecogResultTypeChanging(value);
					this.SendPropertyChanging();
					this._RecogResultType = value;
					this.SendPropertyChanged("RecogResultType");
					this.OnRecogResultTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionStatus", DbType="SmallInt")]
		public System.Nullable<short> TransactionStatus
		{
			get
			{
				return this._TransactionStatus;
			}
			set
			{
				if ((this._TransactionStatus != value))
				{
					this.OnTransactionStatusChanging(value);
					this.SendPropertyChanging();
					this._TransactionStatus = value;
					this.SendPropertyChanged("TransactionStatus");
					this.OnTransactionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecheckStatus", DbType="SmallInt")]
		public System.Nullable<short> PrecheckStatus
		{
			get
			{
				return this._PrecheckStatus;
			}
			set
			{
				if ((this._PrecheckStatus != value))
				{
					this.OnPrecheckStatusChanging(value);
					this.SendPropertyChanging();
					this._PrecheckStatus = value;
					this.SendPropertyChanged("PrecheckStatus");
					this.OnPrecheckStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> PreSupervisionStatus
		{
			get
			{
				return this._PreSupervisionStatus;
			}
			set
			{
				if ((this._PreSupervisionStatus != value))
				{
					this.OnPreSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._PreSupervisionStatus = value;
					this.SendPropertyChanged("PreSupervisionStatus");
					this.OnPreSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> SupervisionStatus
		{
			get
			{
				return this._SupervisionStatus;
			}
			set
			{
				if ((this._SupervisionStatus != value))
				{
					this.OnSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._SupervisionStatus = value;
					this.SendPropertyChanged("SupervisionStatus");
					this.OnSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorID", DbType="Int")]
		public System.Nullable<int> ErrorID
		{
			get
			{
				return this._ErrorID;
			}
			set
			{
				if ((this._ErrorID != value))
				{
					this.OnErrorIDChanging(value);
					this.SendPropertyChanging();
					this._ErrorID = value;
					this.SendPropertyChanged("ErrorID");
					this.OnErrorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIMID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> WIMID
		{
			get
			{
				return this._WIMID;
			}
			set
			{
				if ((this._WIMID != value))
				{
					this.OnWIMIDChanging(value);
					this.SendPropertyChanging();
					this._WIMID = value;
					this.SendPropertyChanged("WIMID");
					this.OnWIMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVehicleInfoManual", DbType="Bit")]
		public System.Nullable<bool> IsVehicleInfoManual
		{
			get
			{
				return this._IsVehicleInfoManual;
			}
			set
			{
				if ((this._IsVehicleInfoManual != value))
				{
					this.OnIsVehicleInfoManualChanging(value);
					this.SendPropertyChanging();
					this._IsVehicleInfoManual = value;
					this.SendPropertyChanged("IsVehicleInfoManual");
					this.OnIsVehicleInfoManualChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OUT_CheckPrepaidCard")]
	public partial class OUT_CheckPrepaidCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _OutCheckPrePaidCardID;
		
		private string _TransactionID;
		
		private string _SmartCardID;
		
		private string _IDCard;
		
		private string _ReceiptNo;
		
		private System.DateTime _CheckDate;
		
		private int _TollFee;
		
		private System.Nullable<int> _BeginBalance;
		
		private System.Nullable<int> _ChargeAmount;
		
		private System.Nullable<int> _Balance;
		
		private System.Nullable<int> _TopUpAmount;
		
		private System.Nullable<int> _CashAmount;
		
		private System.Nullable<int> _TicketTypeID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private System.Nullable<int> _RouteID;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<int> _ShiftID;
		
		private System.Nullable<int> _LaneID;
		
		private System.Nullable<int> _StationID;
		
		private string _ImageID;
		
		private string _RecogPlateNumber;
		
		private string _RegisPlateNumber;
		
		private System.Nullable<short> _RecogResultType;
		
		private System.Nullable<short> _TransactionStatus;
		
		private System.Nullable<short> _PrecheckStatus;
		
		private System.Nullable<short> _PreSupervisionStatus;
		
		private System.Nullable<short> _SupervisionStatus;
		
		private System.Nullable<int> _ErrorID;
		
		private string _EntryPlateNumber;
		
		private System.Nullable<int> _EntryLaneID;
		
		private string _Note;
		
		private System.Nullable<int> _ChargeType;
		
		private System.Nullable<bool> _IsOnlineCheck;
		
		private System.Nullable<int> _ChargeSequenceID;
		
		private System.Nullable<int> _TopUpSequenceID;
		
		private string _SecurityBlock1;
		
		private string _SecurityBlock2;
		
		private string _SecurityBlock3;
		
		private string _F1;
		
		private string _F2;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOutCheckPrePaidCardIDChanging(System.Guid value);
    partial void OnOutCheckPrePaidCardIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnSmartCardIDChanging(string value);
    partial void OnSmartCardIDChanged();
    partial void OnIDCardChanging(string value);
    partial void OnIDCardChanged();
    partial void OnReceiptNoChanging(string value);
    partial void OnReceiptNoChanged();
    partial void OnCheckDateChanging(System.DateTime value);
    partial void OnCheckDateChanged();
    partial void OnTollFeeChanging(int value);
    partial void OnTollFeeChanged();
    partial void OnBeginBalanceChanging(System.Nullable<int> value);
    partial void OnBeginBalanceChanged();
    partial void OnChargeAmountChanging(System.Nullable<int> value);
    partial void OnChargeAmountChanged();
    partial void OnBalanceChanging(System.Nullable<int> value);
    partial void OnBalanceChanged();
    partial void OnTopUpAmountChanging(System.Nullable<int> value);
    partial void OnTopUpAmountChanged();
    partial void OnCashAmountChanging(System.Nullable<int> value);
    partial void OnCashAmountChanged();
    partial void OnTicketTypeIDChanging(System.Nullable<int> value);
    partial void OnTicketTypeIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnRouteIDChanging(System.Nullable<int> value);
    partial void OnRouteIDChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnShiftIDChanging(System.Nullable<int> value);
    partial void OnShiftIDChanged();
    partial void OnLaneIDChanging(System.Nullable<int> value);
    partial void OnLaneIDChanged();
    partial void OnStationIDChanging(System.Nullable<int> value);
    partial void OnStationIDChanged();
    partial void OnImageIDChanging(string value);
    partial void OnImageIDChanged();
    partial void OnRecogPlateNumberChanging(string value);
    partial void OnRecogPlateNumberChanged();
    partial void OnRegisPlateNumberChanging(string value);
    partial void OnRegisPlateNumberChanged();
    partial void OnRecogResultTypeChanging(System.Nullable<short> value);
    partial void OnRecogResultTypeChanged();
    partial void OnTransactionStatusChanging(System.Nullable<short> value);
    partial void OnTransactionStatusChanged();
    partial void OnPrecheckStatusChanging(System.Nullable<short> value);
    partial void OnPrecheckStatusChanged();
    partial void OnPreSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnPreSupervisionStatusChanged();
    partial void OnSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnSupervisionStatusChanged();
    partial void OnErrorIDChanging(System.Nullable<int> value);
    partial void OnErrorIDChanged();
    partial void OnEntryPlateNumberChanging(string value);
    partial void OnEntryPlateNumberChanged();
    partial void OnEntryLaneIDChanging(System.Nullable<int> value);
    partial void OnEntryLaneIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnChargeTypeChanging(System.Nullable<int> value);
    partial void OnChargeTypeChanged();
    partial void OnIsOnlineCheckChanging(System.Nullable<bool> value);
    partial void OnIsOnlineCheckChanged();
    partial void OnChargeSequenceIDChanging(System.Nullable<int> value);
    partial void OnChargeSequenceIDChanged();
    partial void OnTopUpSequenceIDChanging(System.Nullable<int> value);
    partial void OnTopUpSequenceIDChanged();
    partial void OnSecurityBlock1Changing(string value);
    partial void OnSecurityBlock1Changed();
    partial void OnSecurityBlock2Changing(string value);
    partial void OnSecurityBlock2Changed();
    partial void OnSecurityBlock3Changing(string value);
    partial void OnSecurityBlock3Changed();
    partial void OnF1Changing(string value);
    partial void OnF1Changed();
    partial void OnF2Changing(string value);
    partial void OnF2Changed();
    #endregion
		
		public OUT_CheckPrepaidCard()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutCheckPrePaidCardID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid OutCheckPrePaidCardID
		{
			get
			{
				return this._OutCheckPrePaidCardID;
			}
			set
			{
				if ((this._OutCheckPrePaidCardID != value))
				{
					this.OnOutCheckPrePaidCardIDChanging(value);
					this.SendPropertyChanging();
					this._OutCheckPrePaidCardID = value;
					this.SendPropertyChanged("OutCheckPrePaidCardID");
					this.OnOutCheckPrePaidCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmartCardID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SmartCardID
		{
			get
			{
				return this._SmartCardID;
			}
			set
			{
				if ((this._SmartCardID != value))
				{
					this.OnSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._SmartCardID = value;
					this.SendPropertyChanged("SmartCardID");
					this.OnSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCard", DbType="VarChar(32)")]
		public string IDCard
		{
			get
			{
				return this._IDCard;
			}
			set
			{
				if ((this._IDCard != value))
				{
					this.OnIDCardChanging(value);
					this.SendPropertyChanging();
					this._IDCard = value;
					this.SendPropertyChanged("IDCard");
					this.OnIDCardChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNo", DbType="NVarChar(50)")]
		public string ReceiptNo
		{
			get
			{
				return this._ReceiptNo;
			}
			set
			{
				if ((this._ReceiptNo != value))
				{
					this.OnReceiptNoChanging(value);
					this.SendPropertyChanging();
					this._ReceiptNo = value;
					this.SendPropertyChanged("ReceiptNo");
					this.OnReceiptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckDate", DbType="DateTime NOT NULL")]
		public System.DateTime CheckDate
		{
			get
			{
				return this._CheckDate;
			}
			set
			{
				if ((this._CheckDate != value))
				{
					this.OnCheckDateChanging(value);
					this.SendPropertyChanging();
					this._CheckDate = value;
					this.SendPropertyChanged("CheckDate");
					this.OnCheckDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TollFee", DbType="Int NOT NULL")]
		public int TollFee
		{
			get
			{
				return this._TollFee;
			}
			set
			{
				if ((this._TollFee != value))
				{
					this.OnTollFeeChanging(value);
					this.SendPropertyChanging();
					this._TollFee = value;
					this.SendPropertyChanged("TollFee");
					this.OnTollFeeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginBalance", DbType="Int")]
		public System.Nullable<int> BeginBalance
		{
			get
			{
				return this._BeginBalance;
			}
			set
			{
				if ((this._BeginBalance != value))
				{
					this.OnBeginBalanceChanging(value);
					this.SendPropertyChanging();
					this._BeginBalance = value;
					this.SendPropertyChanged("BeginBalance");
					this.OnBeginBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeAmount", DbType="Int")]
		public System.Nullable<int> ChargeAmount
		{
			get
			{
				return this._ChargeAmount;
			}
			set
			{
				if ((this._ChargeAmount != value))
				{
					this.OnChargeAmountChanging(value);
					this.SendPropertyChanging();
					this._ChargeAmount = value;
					this.SendPropertyChanged("ChargeAmount");
					this.OnChargeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopUpAmount", DbType="Int")]
		public System.Nullable<int> TopUpAmount
		{
			get
			{
				return this._TopUpAmount;
			}
			set
			{
				if ((this._TopUpAmount != value))
				{
					this.OnTopUpAmountChanging(value);
					this.SendPropertyChanging();
					this._TopUpAmount = value;
					this.SendPropertyChanged("TopUpAmount");
					this.OnTopUpAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CashAmount", DbType="Int")]
		public System.Nullable<int> CashAmount
		{
			get
			{
				return this._CashAmount;
			}
			set
			{
				if ((this._CashAmount != value))
				{
					this.OnCashAmountChanging(value);
					this.SendPropertyChanging();
					this._CashAmount = value;
					this.SendPropertyChanged("CashAmount");
					this.OnCashAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketTypeID", DbType="Int")]
		public System.Nullable<int> TicketTypeID
		{
			get
			{
				return this._TicketTypeID;
			}
			set
			{
				if ((this._TicketTypeID != value))
				{
					this.OnTicketTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TicketTypeID = value;
					this.SendPropertyChanged("TicketTypeID");
					this.OnTicketTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="Int")]
		public System.Nullable<int> RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="Int")]
		public System.Nullable<int> ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this.OnShiftIDChanging(value);
					this.SendPropertyChanging();
					this._ShiftID = value;
					this.SendPropertyChanged("ShiftID");
					this.OnShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneID", DbType="Int")]
		public System.Nullable<int> LaneID
		{
			get
			{
				return this._LaneID;
			}
			set
			{
				if ((this._LaneID != value))
				{
					this.OnLaneIDChanging(value);
					this.SendPropertyChanging();
					this._LaneID = value;
					this.SendPropertyChanged("LaneID");
					this.OnLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="Int")]
		public System.Nullable<int> StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", DbType="NVarChar(50)")]
		public string ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogPlateNumber", DbType="NVarChar(15)")]
		public string RecogPlateNumber
		{
			get
			{
				return this._RecogPlateNumber;
			}
			set
			{
				if ((this._RecogPlateNumber != value))
				{
					this.OnRecogPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._RecogPlateNumber = value;
					this.SendPropertyChanged("RecogPlateNumber");
					this.OnRecogPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisPlateNumber", DbType="NVarChar(15)")]
		public string RegisPlateNumber
		{
			get
			{
				return this._RegisPlateNumber;
			}
			set
			{
				if ((this._RegisPlateNumber != value))
				{
					this.OnRegisPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._RegisPlateNumber = value;
					this.SendPropertyChanged("RegisPlateNumber");
					this.OnRegisPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogResultType", DbType="SmallInt")]
		public System.Nullable<short> RecogResultType
		{
			get
			{
				return this._RecogResultType;
			}
			set
			{
				if ((this._RecogResultType != value))
				{
					this.OnRecogResultTypeChanging(value);
					this.SendPropertyChanging();
					this._RecogResultType = value;
					this.SendPropertyChanged("RecogResultType");
					this.OnRecogResultTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionStatus", DbType="SmallInt")]
		public System.Nullable<short> TransactionStatus
		{
			get
			{
				return this._TransactionStatus;
			}
			set
			{
				if ((this._TransactionStatus != value))
				{
					this.OnTransactionStatusChanging(value);
					this.SendPropertyChanging();
					this._TransactionStatus = value;
					this.SendPropertyChanged("TransactionStatus");
					this.OnTransactionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecheckStatus", DbType="SmallInt")]
		public System.Nullable<short> PrecheckStatus
		{
			get
			{
				return this._PrecheckStatus;
			}
			set
			{
				if ((this._PrecheckStatus != value))
				{
					this.OnPrecheckStatusChanging(value);
					this.SendPropertyChanging();
					this._PrecheckStatus = value;
					this.SendPropertyChanged("PrecheckStatus");
					this.OnPrecheckStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> PreSupervisionStatus
		{
			get
			{
				return this._PreSupervisionStatus;
			}
			set
			{
				if ((this._PreSupervisionStatus != value))
				{
					this.OnPreSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._PreSupervisionStatus = value;
					this.SendPropertyChanged("PreSupervisionStatus");
					this.OnPreSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> SupervisionStatus
		{
			get
			{
				return this._SupervisionStatus;
			}
			set
			{
				if ((this._SupervisionStatus != value))
				{
					this.OnSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._SupervisionStatus = value;
					this.SendPropertyChanged("SupervisionStatus");
					this.OnSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorID", DbType="Int")]
		public System.Nullable<int> ErrorID
		{
			get
			{
				return this._ErrorID;
			}
			set
			{
				if ((this._ErrorID != value))
				{
					this.OnErrorIDChanging(value);
					this.SendPropertyChanging();
					this._ErrorID = value;
					this.SendPropertyChanged("ErrorID");
					this.OnErrorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryPlateNumber", DbType="NVarChar(15)")]
		public string EntryPlateNumber
		{
			get
			{
				return this._EntryPlateNumber;
			}
			set
			{
				if ((this._EntryPlateNumber != value))
				{
					this.OnEntryPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._EntryPlateNumber = value;
					this.SendPropertyChanged("EntryPlateNumber");
					this.OnEntryPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryLaneID", DbType="Int")]
		public System.Nullable<int> EntryLaneID
		{
			get
			{
				return this._EntryLaneID;
			}
			set
			{
				if ((this._EntryLaneID != value))
				{
					this.OnEntryLaneIDChanging(value);
					this.SendPropertyChanging();
					this._EntryLaneID = value;
					this.SendPropertyChanged("EntryLaneID");
					this.OnEntryLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeType", DbType="Int")]
		public System.Nullable<int> ChargeType
		{
			get
			{
				return this._ChargeType;
			}
			set
			{
				if ((this._ChargeType != value))
				{
					this.OnChargeTypeChanging(value);
					this.SendPropertyChanging();
					this._ChargeType = value;
					this.SendPropertyChanged("ChargeType");
					this.OnChargeTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOnlineCheck", DbType="Bit")]
		public System.Nullable<bool> IsOnlineCheck
		{
			get
			{
				return this._IsOnlineCheck;
			}
			set
			{
				if ((this._IsOnlineCheck != value))
				{
					this.OnIsOnlineCheckChanging(value);
					this.SendPropertyChanging();
					this._IsOnlineCheck = value;
					this.SendPropertyChanged("IsOnlineCheck");
					this.OnIsOnlineCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeSequenceID", DbType="Int")]
		public System.Nullable<int> ChargeSequenceID
		{
			get
			{
				return this._ChargeSequenceID;
			}
			set
			{
				if ((this._ChargeSequenceID != value))
				{
					this.OnChargeSequenceIDChanging(value);
					this.SendPropertyChanging();
					this._ChargeSequenceID = value;
					this.SendPropertyChanged("ChargeSequenceID");
					this.OnChargeSequenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TopUpSequenceID", DbType="Int")]
		public System.Nullable<int> TopUpSequenceID
		{
			get
			{
				return this._TopUpSequenceID;
			}
			set
			{
				if ((this._TopUpSequenceID != value))
				{
					this.OnTopUpSequenceIDChanging(value);
					this.SendPropertyChanging();
					this._TopUpSequenceID = value;
					this.SendPropertyChanged("TopUpSequenceID");
					this.OnTopUpSequenceIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityBlock1", DbType="NVarChar(50)")]
		public string SecurityBlock1
		{
			get
			{
				return this._SecurityBlock1;
			}
			set
			{
				if ((this._SecurityBlock1 != value))
				{
					this.OnSecurityBlock1Changing(value);
					this.SendPropertyChanging();
					this._SecurityBlock1 = value;
					this.SendPropertyChanged("SecurityBlock1");
					this.OnSecurityBlock1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityBlock2", DbType="NVarChar(50)")]
		public string SecurityBlock2
		{
			get
			{
				return this._SecurityBlock2;
			}
			set
			{
				if ((this._SecurityBlock2 != value))
				{
					this.OnSecurityBlock2Changing(value);
					this.SendPropertyChanging();
					this._SecurityBlock2 = value;
					this.SendPropertyChanged("SecurityBlock2");
					this.OnSecurityBlock2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SecurityBlock3", DbType="NVarChar(50)")]
		public string SecurityBlock3
		{
			get
			{
				return this._SecurityBlock3;
			}
			set
			{
				if ((this._SecurityBlock3 != value))
				{
					this.OnSecurityBlock3Changing(value);
					this.SendPropertyChanging();
					this._SecurityBlock3 = value;
					this.SendPropertyChanged("SecurityBlock3");
					this.OnSecurityBlock3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F1", DbType="NVarChar(50)")]
		public string F1
		{
			get
			{
				return this._F1;
			}
			set
			{
				if ((this._F1 != value))
				{
					this.OnF1Changing(value);
					this.SendPropertyChanging();
					this._F1 = value;
					this.SendPropertyChanged("F1");
					this.OnF1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F2", DbType="NVarChar(50)")]
		public string F2
		{
			get
			{
				return this._F2;
			}
			set
			{
				if ((this._F2 != value))
				{
					this.OnF2Changing(value);
					this.SendPropertyChanging();
					this._F2 = value;
					this.SendPropertyChanged("F2");
					this.OnF2Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.OUT_CheckSmartCard")]
	public partial class OUT_CheckSmartCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _OutCheckSmartCardID;
		
		private string _TransactionID;
		
		private string _ReceiptNo;
		
		private string _SmartCardID;
		
		private System.Nullable<System.Guid> _InCheckSmartCardID;
		
		private System.Nullable<System.Guid> _InCheckSmartCardIDManual;
		
		private System.DateTime _CheckDate;
		
		private System.Nullable<int> _BeginBalance;
		
		private System.Nullable<int> _ChargeAmount;
		
		private System.Nullable<int> _Balance;
		
		private System.Nullable<int> _TicketTypeID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private System.Nullable<int> _RouteID;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<int> _ShiftID;
		
		private System.Nullable<int> _LaneID;
		
		private System.Nullable<int> _StationID;
		
		private string _ImageID;
		
		private string _RecogPlateNumber;
		
		private System.Nullable<short> _RecogResultType;
		
		private System.Nullable<short> _TransactionStatus;
		
		private System.Nullable<short> _PrecheckStatus;
		
		private System.Nullable<short> _PreSupervisionStatus;
		
		private System.Nullable<short> _SupervisionStatus;
		
		private System.Nullable<int> _ErrorID;
		
		private string _Note;
		
		private string _EntryPlateNumber;
		
		private System.Nullable<int> _EntryLaneID;
		
		private string _F1;
		
		private string _F2;
		
		private EntityRef<IN_CheckSmartCard> _IN_CheckSmartCard;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOutCheckSmartCardIDChanging(System.Guid value);
    partial void OnOutCheckSmartCardIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnReceiptNoChanging(string value);
    partial void OnReceiptNoChanged();
    partial void OnSmartCardIDChanging(string value);
    partial void OnSmartCardIDChanged();
    partial void OnInCheckSmartCardIDChanging(System.Nullable<System.Guid> value);
    partial void OnInCheckSmartCardIDChanged();
    partial void OnInCheckSmartCardIDManualChanging(System.Nullable<System.Guid> value);
    partial void OnInCheckSmartCardIDManualChanged();
    partial void OnCheckDateChanging(System.DateTime value);
    partial void OnCheckDateChanged();
    partial void OnBeginBalanceChanging(System.Nullable<int> value);
    partial void OnBeginBalanceChanged();
    partial void OnChargeAmountChanging(System.Nullable<int> value);
    partial void OnChargeAmountChanged();
    partial void OnBalanceChanging(System.Nullable<int> value);
    partial void OnBalanceChanged();
    partial void OnTicketTypeIDChanging(System.Nullable<int> value);
    partial void OnTicketTypeIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnRouteIDChanging(System.Nullable<int> value);
    partial void OnRouteIDChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnShiftIDChanging(System.Nullable<int> value);
    partial void OnShiftIDChanged();
    partial void OnLaneIDChanging(System.Nullable<int> value);
    partial void OnLaneIDChanged();
    partial void OnStationIDChanging(System.Nullable<int> value);
    partial void OnStationIDChanged();
    partial void OnImageIDChanging(string value);
    partial void OnImageIDChanged();
    partial void OnRecogPlateNumberChanging(string value);
    partial void OnRecogPlateNumberChanged();
    partial void OnRecogResultTypeChanging(System.Nullable<short> value);
    partial void OnRecogResultTypeChanged();
    partial void OnTransactionStatusChanging(System.Nullable<short> value);
    partial void OnTransactionStatusChanged();
    partial void OnPrecheckStatusChanging(System.Nullable<short> value);
    partial void OnPrecheckStatusChanged();
    partial void OnPreSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnPreSupervisionStatusChanged();
    partial void OnSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnSupervisionStatusChanged();
    partial void OnErrorIDChanging(System.Nullable<int> value);
    partial void OnErrorIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnEntryPlateNumberChanging(string value);
    partial void OnEntryPlateNumberChanged();
    partial void OnEntryLaneIDChanging(System.Nullable<int> value);
    partial void OnEntryLaneIDChanged();
    partial void OnF1Changing(string value);
    partial void OnF1Changed();
    partial void OnF2Changing(string value);
    partial void OnF2Changed();
    #endregion
		
		public OUT_CheckSmartCard()
		{
			this._IN_CheckSmartCard = default(EntityRef<IN_CheckSmartCard>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OutCheckSmartCardID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid OutCheckSmartCardID
		{
			get
			{
				return this._OutCheckSmartCardID;
			}
			set
			{
				if ((this._OutCheckSmartCardID != value))
				{
					this.OnOutCheckSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._OutCheckSmartCardID = value;
					this.SendPropertyChanged("OutCheckSmartCardID");
					this.OnOutCheckSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ReceiptNo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ReceiptNo
		{
			get
			{
				return this._ReceiptNo;
			}
			set
			{
				if ((this._ReceiptNo != value))
				{
					this.OnReceiptNoChanging(value);
					this.SendPropertyChanging();
					this._ReceiptNo = value;
					this.SendPropertyChanged("ReceiptNo");
					this.OnReceiptNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmartCardID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SmartCardID
		{
			get
			{
				return this._SmartCardID;
			}
			set
			{
				if ((this._SmartCardID != value))
				{
					this.OnSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._SmartCardID = value;
					this.SendPropertyChanged("SmartCardID");
					this.OnSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InCheckSmartCardID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> InCheckSmartCardID
		{
			get
			{
				return this._InCheckSmartCardID;
			}
			set
			{
				if ((this._InCheckSmartCardID != value))
				{
					if (this._IN_CheckSmartCard.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnInCheckSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._InCheckSmartCardID = value;
					this.SendPropertyChanged("InCheckSmartCardID");
					this.OnInCheckSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InCheckSmartCardIDManual", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> InCheckSmartCardIDManual
		{
			get
			{
				return this._InCheckSmartCardIDManual;
			}
			set
			{
				if ((this._InCheckSmartCardIDManual != value))
				{
					this.OnInCheckSmartCardIDManualChanging(value);
					this.SendPropertyChanging();
					this._InCheckSmartCardIDManual = value;
					this.SendPropertyChanged("InCheckSmartCardIDManual");
					this.OnInCheckSmartCardIDManualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckDate", DbType="DateTime NOT NULL")]
		public System.DateTime CheckDate
		{
			get
			{
				return this._CheckDate;
			}
			set
			{
				if ((this._CheckDate != value))
				{
					this.OnCheckDateChanging(value);
					this.SendPropertyChanging();
					this._CheckDate = value;
					this.SendPropertyChanged("CheckDate");
					this.OnCheckDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BeginBalance", DbType="Int")]
		public System.Nullable<int> BeginBalance
		{
			get
			{
				return this._BeginBalance;
			}
			set
			{
				if ((this._BeginBalance != value))
				{
					this.OnBeginBalanceChanging(value);
					this.SendPropertyChanging();
					this._BeginBalance = value;
					this.SendPropertyChanged("BeginBalance");
					this.OnBeginBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChargeAmount", DbType="Int")]
		public System.Nullable<int> ChargeAmount
		{
			get
			{
				return this._ChargeAmount;
			}
			set
			{
				if ((this._ChargeAmount != value))
				{
					this.OnChargeAmountChanging(value);
					this.SendPropertyChanging();
					this._ChargeAmount = value;
					this.SendPropertyChanged("ChargeAmount");
					this.OnChargeAmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Balance", DbType="Int")]
		public System.Nullable<int> Balance
		{
			get
			{
				return this._Balance;
			}
			set
			{
				if ((this._Balance != value))
				{
					this.OnBalanceChanging(value);
					this.SendPropertyChanging();
					this._Balance = value;
					this.SendPropertyChanged("Balance");
					this.OnBalanceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketTypeID", DbType="Int")]
		public System.Nullable<int> TicketTypeID
		{
			get
			{
				return this._TicketTypeID;
			}
			set
			{
				if ((this._TicketTypeID != value))
				{
					this.OnTicketTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TicketTypeID = value;
					this.SendPropertyChanged("TicketTypeID");
					this.OnTicketTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="Int")]
		public System.Nullable<int> RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="Int")]
		public System.Nullable<int> ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this.OnShiftIDChanging(value);
					this.SendPropertyChanging();
					this._ShiftID = value;
					this.SendPropertyChanged("ShiftID");
					this.OnShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneID", DbType="Int")]
		public System.Nullable<int> LaneID
		{
			get
			{
				return this._LaneID;
			}
			set
			{
				if ((this._LaneID != value))
				{
					this.OnLaneIDChanging(value);
					this.SendPropertyChanging();
					this._LaneID = value;
					this.SendPropertyChanged("LaneID");
					this.OnLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="Int")]
		public System.Nullable<int> StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", DbType="NVarChar(50)")]
		public string ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogPlateNumber", DbType="NVarChar(15)")]
		public string RecogPlateNumber
		{
			get
			{
				return this._RecogPlateNumber;
			}
			set
			{
				if ((this._RecogPlateNumber != value))
				{
					this.OnRecogPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._RecogPlateNumber = value;
					this.SendPropertyChanged("RecogPlateNumber");
					this.OnRecogPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogResultType", DbType="SmallInt")]
		public System.Nullable<short> RecogResultType
		{
			get
			{
				return this._RecogResultType;
			}
			set
			{
				if ((this._RecogResultType != value))
				{
					this.OnRecogResultTypeChanging(value);
					this.SendPropertyChanging();
					this._RecogResultType = value;
					this.SendPropertyChanged("RecogResultType");
					this.OnRecogResultTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionStatus", DbType="SmallInt")]
		public System.Nullable<short> TransactionStatus
		{
			get
			{
				return this._TransactionStatus;
			}
			set
			{
				if ((this._TransactionStatus != value))
				{
					this.OnTransactionStatusChanging(value);
					this.SendPropertyChanging();
					this._TransactionStatus = value;
					this.SendPropertyChanged("TransactionStatus");
					this.OnTransactionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecheckStatus", DbType="SmallInt")]
		public System.Nullable<short> PrecheckStatus
		{
			get
			{
				return this._PrecheckStatus;
			}
			set
			{
				if ((this._PrecheckStatus != value))
				{
					this.OnPrecheckStatusChanging(value);
					this.SendPropertyChanging();
					this._PrecheckStatus = value;
					this.SendPropertyChanged("PrecheckStatus");
					this.OnPrecheckStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> PreSupervisionStatus
		{
			get
			{
				return this._PreSupervisionStatus;
			}
			set
			{
				if ((this._PreSupervisionStatus != value))
				{
					this.OnPreSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._PreSupervisionStatus = value;
					this.SendPropertyChanged("PreSupervisionStatus");
					this.OnPreSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> SupervisionStatus
		{
			get
			{
				return this._SupervisionStatus;
			}
			set
			{
				if ((this._SupervisionStatus != value))
				{
					this.OnSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._SupervisionStatus = value;
					this.SendPropertyChanged("SupervisionStatus");
					this.OnSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorID", DbType="Int")]
		public System.Nullable<int> ErrorID
		{
			get
			{
				return this._ErrorID;
			}
			set
			{
				if ((this._ErrorID != value))
				{
					this.OnErrorIDChanging(value);
					this.SendPropertyChanging();
					this._ErrorID = value;
					this.SendPropertyChanged("ErrorID");
					this.OnErrorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryPlateNumber", DbType="NVarChar(15)")]
		public string EntryPlateNumber
		{
			get
			{
				return this._EntryPlateNumber;
			}
			set
			{
				if ((this._EntryPlateNumber != value))
				{
					this.OnEntryPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._EntryPlateNumber = value;
					this.SendPropertyChanged("EntryPlateNumber");
					this.OnEntryPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EntryLaneID", DbType="Int")]
		public System.Nullable<int> EntryLaneID
		{
			get
			{
				return this._EntryLaneID;
			}
			set
			{
				if ((this._EntryLaneID != value))
				{
					this.OnEntryLaneIDChanging(value);
					this.SendPropertyChanging();
					this._EntryLaneID = value;
					this.SendPropertyChanged("EntryLaneID");
					this.OnEntryLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F1", DbType="NVarChar(50)")]
		public string F1
		{
			get
			{
				return this._F1;
			}
			set
			{
				if ((this._F1 != value))
				{
					this.OnF1Changing(value);
					this.SendPropertyChanging();
					this._F1 = value;
					this.SendPropertyChanged("F1");
					this.OnF1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_F2", DbType="NVarChar(50)")]
		public string F2
		{
			get
			{
				return this._F2;
			}
			set
			{
				if ((this._F2 != value))
				{
					this.OnF2Changing(value);
					this.SendPropertyChanging();
					this._F2 = value;
					this.SendPropertyChanged("F2");
					this.OnF2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IN_CheckSmartCard_OUT_CheckSmartCard", Storage="_IN_CheckSmartCard", ThisKey="InCheckSmartCardID", OtherKey="InCheckSmartCardID", IsForeignKey=true)]
		public IN_CheckSmartCard IN_CheckSmartCard
		{
			get
			{
				return this._IN_CheckSmartCard.Entity;
			}
			set
			{
				IN_CheckSmartCard previousValue = this._IN_CheckSmartCard.Entity;
				if (((previousValue != value) 
							|| (this._IN_CheckSmartCard.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._IN_CheckSmartCard.Entity = null;
						previousValue.OUT_CheckSmartCards.Remove(this);
					}
					this._IN_CheckSmartCard.Entity = value;
					if ((value != null))
					{
						value.OUT_CheckSmartCards.Add(this);
						this._InCheckSmartCardID = value.InCheckSmartCardID;
					}
					else
					{
						this._InCheckSmartCardID = default(Nullable<System.Guid>);
					}
					this.SendPropertyChanged("IN_CheckSmartCard");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.IN_CheckSmartCard")]
	public partial class IN_CheckSmartCard : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _InCheckSmartCardID;
		
		private string _TransactionID;
		
		private string _SmartCardID;
		
		private System.DateTime _CheckDate;
		
		private System.Nullable<int> _TicketTypeID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private System.Nullable<int> _EmployeeID;
		
		private System.Nullable<int> _ShiftID;
		
		private System.Nullable<int> _LaneID;
		
		private System.Nullable<int> _StationID;
		
		private string _ImageID;
		
		private string _RecogPlateNumber;
		
		private System.Nullable<short> _RecogResultType;
		
		private System.Nullable<short> _TransactionStatus;
		
		private System.Nullable<short> _PrecheckStatus;
		
		private System.Nullable<short> _PreSupervisionStatus;
		
		private System.Nullable<short> _SupervisionStatus;
		
		private System.Nullable<int> _ErrorID;
		
		private System.Nullable<System.Guid> _WIMID;
		
		private string _Note;
		
		private System.Nullable<bool> _IsVehicleInfoManual;
		
		private EntitySet<OUT_CheckSmartCard> _OUT_CheckSmartCards;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInCheckSmartCardIDChanging(System.Guid value);
    partial void OnInCheckSmartCardIDChanged();
    partial void OnTransactionIDChanging(string value);
    partial void OnTransactionIDChanged();
    partial void OnSmartCardIDChanging(string value);
    partial void OnSmartCardIDChanged();
    partial void OnCheckDateChanging(System.DateTime value);
    partial void OnCheckDateChanged();
    partial void OnTicketTypeIDChanging(System.Nullable<int> value);
    partial void OnTicketTypeIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnEmployeeIDChanging(System.Nullable<int> value);
    partial void OnEmployeeIDChanged();
    partial void OnShiftIDChanging(System.Nullable<int> value);
    partial void OnShiftIDChanged();
    partial void OnLaneIDChanging(System.Nullable<int> value);
    partial void OnLaneIDChanged();
    partial void OnStationIDChanging(System.Nullable<int> value);
    partial void OnStationIDChanged();
    partial void OnImageIDChanging(string value);
    partial void OnImageIDChanged();
    partial void OnRecogPlateNumberChanging(string value);
    partial void OnRecogPlateNumberChanged();
    partial void OnRecogResultTypeChanging(System.Nullable<short> value);
    partial void OnRecogResultTypeChanged();
    partial void OnTransactionStatusChanging(System.Nullable<short> value);
    partial void OnTransactionStatusChanged();
    partial void OnPrecheckStatusChanging(System.Nullable<short> value);
    partial void OnPrecheckStatusChanged();
    partial void OnPreSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnPreSupervisionStatusChanged();
    partial void OnSupervisionStatusChanging(System.Nullable<short> value);
    partial void OnSupervisionStatusChanged();
    partial void OnErrorIDChanging(System.Nullable<int> value);
    partial void OnErrorIDChanged();
    partial void OnWIMIDChanging(System.Nullable<System.Guid> value);
    partial void OnWIMIDChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnIsVehicleInfoManualChanging(System.Nullable<bool> value);
    partial void OnIsVehicleInfoManualChanged();
    #endregion
		
		public IN_CheckSmartCard()
		{
			this._OUT_CheckSmartCards = new EntitySet<OUT_CheckSmartCard>(new Action<OUT_CheckSmartCard>(this.attach_OUT_CheckSmartCards), new Action<OUT_CheckSmartCard>(this.detach_OUT_CheckSmartCards));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InCheckSmartCardID", DbType="UniqueIdentifier NOT NULL", IsPrimaryKey=true)]
		public System.Guid InCheckSmartCardID
		{
			get
			{
				return this._InCheckSmartCardID;
			}
			set
			{
				if ((this._InCheckSmartCardID != value))
				{
					this.OnInCheckSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._InCheckSmartCardID = value;
					this.SendPropertyChanged("InCheckSmartCardID");
					this.OnInCheckSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionID", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string TransactionID
		{
			get
			{
				return this._TransactionID;
			}
			set
			{
				if ((this._TransactionID != value))
				{
					this.OnTransactionIDChanging(value);
					this.SendPropertyChanging();
					this._TransactionID = value;
					this.SendPropertyChanged("TransactionID");
					this.OnTransactionIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SmartCardID", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string SmartCardID
		{
			get
			{
				return this._SmartCardID;
			}
			set
			{
				if ((this._SmartCardID != value))
				{
					this.OnSmartCardIDChanging(value);
					this.SendPropertyChanging();
					this._SmartCardID = value;
					this.SendPropertyChanged("SmartCardID");
					this.OnSmartCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CheckDate", DbType="DateTime NOT NULL")]
		public System.DateTime CheckDate
		{
			get
			{
				return this._CheckDate;
			}
			set
			{
				if ((this._CheckDate != value))
				{
					this.OnCheckDateChanging(value);
					this.SendPropertyChanging();
					this._CheckDate = value;
					this.SendPropertyChanged("CheckDate");
					this.OnCheckDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TicketTypeID", DbType="Int")]
		public System.Nullable<int> TicketTypeID
		{
			get
			{
				return this._TicketTypeID;
			}
			set
			{
				if ((this._TicketTypeID != value))
				{
					this.OnTicketTypeIDChanging(value);
					this.SendPropertyChanging();
					this._TicketTypeID = value;
					this.SendPropertyChanged("TicketTypeID");
					this.OnTicketTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EmployeeID", DbType="Int")]
		public System.Nullable<int> EmployeeID
		{
			get
			{
				return this._EmployeeID;
			}
			set
			{
				if ((this._EmployeeID != value))
				{
					this.OnEmployeeIDChanging(value);
					this.SendPropertyChanging();
					this._EmployeeID = value;
					this.SendPropertyChanged("EmployeeID");
					this.OnEmployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShiftID", DbType="Int")]
		public System.Nullable<int> ShiftID
		{
			get
			{
				return this._ShiftID;
			}
			set
			{
				if ((this._ShiftID != value))
				{
					this.OnShiftIDChanging(value);
					this.SendPropertyChanging();
					this._ShiftID = value;
					this.SendPropertyChanged("ShiftID");
					this.OnShiftIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneID", DbType="Int")]
		public System.Nullable<int> LaneID
		{
			get
			{
				return this._LaneID;
			}
			set
			{
				if ((this._LaneID != value))
				{
					this.OnLaneIDChanging(value);
					this.SendPropertyChanging();
					this._LaneID = value;
					this.SendPropertyChanged("LaneID");
					this.OnLaneIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationID", DbType="Int")]
		public System.Nullable<int> StationID
		{
			get
			{
				return this._StationID;
			}
			set
			{
				if ((this._StationID != value))
				{
					this.OnStationIDChanging(value);
					this.SendPropertyChanging();
					this._StationID = value;
					this.SendPropertyChanged("StationID");
					this.OnStationIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ImageID", DbType="NVarChar(50)")]
		public string ImageID
		{
			get
			{
				return this._ImageID;
			}
			set
			{
				if ((this._ImageID != value))
				{
					this.OnImageIDChanging(value);
					this.SendPropertyChanging();
					this._ImageID = value;
					this.SendPropertyChanged("ImageID");
					this.OnImageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogPlateNumber", DbType="NVarChar(15)")]
		public string RecogPlateNumber
		{
			get
			{
				return this._RecogPlateNumber;
			}
			set
			{
				if ((this._RecogPlateNumber != value))
				{
					this.OnRecogPlateNumberChanging(value);
					this.SendPropertyChanging();
					this._RecogPlateNumber = value;
					this.SendPropertyChanged("RecogPlateNumber");
					this.OnRecogPlateNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RecogResultType", DbType="SmallInt")]
		public System.Nullable<short> RecogResultType
		{
			get
			{
				return this._RecogResultType;
			}
			set
			{
				if ((this._RecogResultType != value))
				{
					this.OnRecogResultTypeChanging(value);
					this.SendPropertyChanging();
					this._RecogResultType = value;
					this.SendPropertyChanged("RecogResultType");
					this.OnRecogResultTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TransactionStatus", DbType="SmallInt")]
		public System.Nullable<short> TransactionStatus
		{
			get
			{
				return this._TransactionStatus;
			}
			set
			{
				if ((this._TransactionStatus != value))
				{
					this.OnTransactionStatusChanging(value);
					this.SendPropertyChanging();
					this._TransactionStatus = value;
					this.SendPropertyChanged("TransactionStatus");
					this.OnTransactionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrecheckStatus", DbType="SmallInt")]
		public System.Nullable<short> PrecheckStatus
		{
			get
			{
				return this._PrecheckStatus;
			}
			set
			{
				if ((this._PrecheckStatus != value))
				{
					this.OnPrecheckStatusChanging(value);
					this.SendPropertyChanging();
					this._PrecheckStatus = value;
					this.SendPropertyChanged("PrecheckStatus");
					this.OnPrecheckStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreSupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> PreSupervisionStatus
		{
			get
			{
				return this._PreSupervisionStatus;
			}
			set
			{
				if ((this._PreSupervisionStatus != value))
				{
					this.OnPreSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._PreSupervisionStatus = value;
					this.SendPropertyChanged("PreSupervisionStatus");
					this.OnPreSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupervisionStatus", DbType="SmallInt")]
		public System.Nullable<short> SupervisionStatus
		{
			get
			{
				return this._SupervisionStatus;
			}
			set
			{
				if ((this._SupervisionStatus != value))
				{
					this.OnSupervisionStatusChanging(value);
					this.SendPropertyChanging();
					this._SupervisionStatus = value;
					this.SendPropertyChanged("SupervisionStatus");
					this.OnSupervisionStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ErrorID", DbType="Int")]
		public System.Nullable<int> ErrorID
		{
			get
			{
				return this._ErrorID;
			}
			set
			{
				if ((this._ErrorID != value))
				{
					this.OnErrorIDChanging(value);
					this.SendPropertyChanging();
					this._ErrorID = value;
					this.SendPropertyChanged("ErrorID");
					this.OnErrorIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WIMID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> WIMID
		{
			get
			{
				return this._WIMID;
			}
			set
			{
				if ((this._WIMID != value))
				{
					this.OnWIMIDChanging(value);
					this.SendPropertyChanging();
					this._WIMID = value;
					this.SendPropertyChanged("WIMID");
					this.OnWIMIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(100)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsVehicleInfoManual", DbType="Bit")]
		public System.Nullable<bool> IsVehicleInfoManual
		{
			get
			{
				return this._IsVehicleInfoManual;
			}
			set
			{
				if ((this._IsVehicleInfoManual != value))
				{
					this.OnIsVehicleInfoManualChanging(value);
					this.SendPropertyChanging();
					this._IsVehicleInfoManual = value;
					this.SendPropertyChanged("IsVehicleInfoManual");
					this.OnIsVehicleInfoManualChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="IN_CheckSmartCard_OUT_CheckSmartCard", Storage="_OUT_CheckSmartCards", ThisKey="InCheckSmartCardID", OtherKey="InCheckSmartCardID")]
		public EntitySet<OUT_CheckSmartCard> OUT_CheckSmartCards
		{
			get
			{
				return this._OUT_CheckSmartCards;
			}
			set
			{
				this._OUT_CheckSmartCards.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_OUT_CheckSmartCards(OUT_CheckSmartCard entity)
		{
			this.SendPropertyChanging();
			entity.IN_CheckSmartCard = this;
		}
		
		private void detach_OUT_CheckSmartCards(OUT_CheckSmartCard entity)
		{
			this.SendPropertyChanging();
			entity.IN_CheckSmartCard = null;
		}
	}
}
#pragma warning restore 1591
