<?xml version="1.0" encoding="utf-8"?><Database Name="HPE" Class="QLHPDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=SOFT-W\MSSQLSERVER2K14;Initial Catalog=HPE;Persist Security Info=True;User ID=sv2" SettingsObjectName="TollTicketManagement.Properties.Settings" SettingsPropertyName="HPEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LS_VehicleType" Member="LS_VehicleTypes">
    <Type Name="LS_VehicleType">
      <Column Name="VehicleTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="VehicleTypeCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="AmountPerKm" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LS_VehicleType_IN_CheckSmartCard" Member="IN_CheckSmartCards" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="IN_CheckSmartCard" />
      <Association Name="LS_VehicleType_AC_PPCWhiteList" Member="AC_PPCWhiteLists" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="AC_PPCWhiteList" />
      <Association Name="LS_VehicleType_AC_TollWhiteList" Member="AC_TollWhiteLists" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="AC_TollWhiteList" />
    </Type>
  </Table>
  <Table Name="dbo.LS_Lane" Member="LS_Lanes">
    <Type Name="LS_Lane">
      <Column Name="LaneID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LaneCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="DirectionType" Type="System.Int16" DbType="SmallInt NOT NULL" CanBeNull="false" />
      <Column Name="LaneType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LS_Lane_IN_CheckSmartCard" Member="IN_CheckSmartCards" ThisKey="LaneID" OtherKey="LaneID" Type="IN_CheckSmartCard" />
      <Association Name="LS_Lane_OUT_CheckSmartCard" Member="OUT_CheckSmartCards" ThisKey="LaneID" OtherKey="LaneID" Type="OUT_CheckSmartCard" />
      <Association Name="LS_Lane_AC_PPCWhiteList" Member="AC_PPCWhiteLists1" ThisKey="LaneID" OtherKey="LaneIDIn" Type="AC_PPCWhiteList" />
      <Association Name="LS_Lane_AC_PPCWhiteList1" Member="AC_PPCWhiteLists" ThisKey="LaneID" OtherKey="LaneIDOut" Type="AC_PPCWhiteList" />
      <Association Name="LS_Lane_AC_TollWhiteList" Member="AC_TollWhiteLists1" ThisKey="LaneID" OtherKey="LaneIDIn" Type="AC_TollWhiteList" />
      <Association Name="LS_Lane_AC_TollWhiteList1" Member="AC_TollWhiteLists" ThisKey="LaneID" OtherKey="LaneIDOut" Type="AC_TollWhiteList" />
      <Association Name="LS_Station_LS_Lane" Member="LS_Station" ThisKey="StationID" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LS_Station" Member="LS_Stations">
    <Type Name="LS_Station">
      <Column Name="StationID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StationCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="CompanyID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StationType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="Telephone" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Fax" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LS_Station_LS_Lane" Member="LS_Lanes" ThisKey="StationID" OtherKey="StationID" Type="LS_Lane" />
      <Association Name="LS_Station_LS_Route" Member="LS_Routes1" ThisKey="StationID" OtherKey="ToStationID" Type="LS_Route" />
      <Association Name="LS_Station_LS_Route1" Member="LS_Routes" ThisKey="StationID" OtherKey="FromStationID" Type="LS_Route" />
      <Association Name="LS_Station_IN_CheckSmartCard" Member="IN_CheckSmartCards" ThisKey="StationID" OtherKey="StationID" Type="IN_CheckSmartCard" />
      <Association Name="LS_Station_OUT_CheckSmartCard" Member="OUT_CheckSmartCards" ThisKey="StationID" OtherKey="StationID" Type="OUT_CheckSmartCard" />
      <Association Name="LS_Station_AC_PPCWhiteList" Member="AC_PPCWhiteLists1" ThisKey="StationID" OtherKey="StationIDIn" Type="AC_PPCWhiteList" />
      <Association Name="LS_Station_AC_PPCWhiteList1" Member="AC_PPCWhiteLists" ThisKey="StationID" OtherKey="StationIDOut" Type="AC_PPCWhiteList" />
      <Association Name="LS_Station_AC_TollWhiteList" Member="AC_TollWhiteLists1" ThisKey="StationID" OtherKey="StationIDIn" Type="AC_TollWhiteList" />
      <Association Name="LS_Station_AC_TollWhiteList1" Member="AC_TollWhiteLists" ThisKey="StationID" OtherKey="LaneIDOut" Type="AC_TollWhiteList" />
    </Type>
  </Table>
  <Table Name="dbo.LS_Route" Member="LS_Routes">
    <Type Name="LS_Route">
      <Column Name="RouteID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="RouteCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="FromStationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ToStationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Length" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsMaxLength" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="LS_Route_OUT_CheckSmartCard" Member="OUT_CheckSmartCards" ThisKey="RouteID" OtherKey="RouteID" Type="OUT_CheckSmartCard" />
      <Association Name="LS_Route_AC_PPCWhiteList" Member="AC_PPCWhiteLists" ThisKey="RouteID" OtherKey="RouteID" Type="AC_PPCWhiteList" />
      <Association Name="LS_Route_AC_TollWhiteList" Member="AC_TollWhiteLists" ThisKey="RouteID" OtherKey="RouteID" Type="AC_TollWhiteList" />
      <Association Name="LS_Station_LS_Route" Member="LS_Station1" ThisKey="ToStationID" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Station_LS_Route1" Member="LS_Station" ThisKey="FromStationID" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.IN_CheckSmartCard" Member="IN_CheckSmartCards">
    <Type Name="IN_CheckSmartCard">
      <Column Name="InCheckSmartCardID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="SmartCardID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="TicketTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VehicleTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShiftID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecogPlateNumber" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="RecogResultType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TransactionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PrecheckStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PreSupervisionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SupervisionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ErrorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WIMID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="IsVehicleInfoManual" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="IN_CheckSmartCard_OUT_CheckSmartCard" Member="OUT_CheckSmartCards" ThisKey="InCheckSmartCardID" OtherKey="InCheckSmartCardID" Type="OUT_CheckSmartCard" />
      <Association Name="LS_Lane_IN_CheckSmartCard" Member="LS_Lane" ThisKey="LaneID" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Station_IN_CheckSmartCard" Member="LS_Station" ThisKey="StationID" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_VehicleType_IN_CheckSmartCard" Member="LS_VehicleType" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="LS_VehicleType" IsForeignKey="true" />
      <Association Name="LS_Employee_IN_CheckSmartCard" Member="LS_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OUT_CheckSmartCard" Member="OUT_CheckSmartCards">
    <Type Name="OUT_CheckSmartCard">
      <Column Name="OutCheckSmartCardID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TransactionID" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="ReceiptNo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SmartCardID" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="InCheckSmartCardID" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="InCheckSmartCardIDManual" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="CheckDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="BeginBalance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChargeAmount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Balance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TicketTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VehicleTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RouteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShiftID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ImageID" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RecogPlateNumber" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="RecogResultType" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="TransactionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PrecheckStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="PreSupervisionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="SupervisionStatus" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="ErrorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EntryPlateNumber" Type="System.String" DbType="NVarChar(15)" CanBeNull="true" />
      <Column Name="EntryLaneID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="F1" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="F2" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="IN_CheckSmartCard_OUT_CheckSmartCard" Member="IN_CheckSmartCard" ThisKey="InCheckSmartCardID" OtherKey="InCheckSmartCardID" Type="IN_CheckSmartCard" IsForeignKey="true" />
      <Association Name="LS_Lane_OUT_CheckSmartCard" Member="LS_Lane" ThisKey="LaneID" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Station_OUT_CheckSmartCard" Member="LS_Station" ThisKey="StationID" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Route_OUT_CheckSmartCard" Member="LS_Route" ThisKey="RouteID" OtherKey="RouteID" Type="LS_Route" IsForeignKey="true" />
      <Association Name="LS_Employee_OUT_CheckSmartCard" Member="LS_Employee" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.AC_PPCWhiteList" Member="AC_PPCWhiteLists">
    <Type Name="AC_PPCWhiteList">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CardID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VehicleTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormatID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VehiclePlateIn" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StationIDIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneIDIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastCheckDateIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VehiclePlateOut" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StationIDOut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneIDOut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastCheckDateOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RouteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Hour" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockEmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LockDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UnlockEmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnlockDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsLost" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImageIDIn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImageIDOut" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LS_VehicleType_AC_PPCWhiteList" Member="LS_VehicleType" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="LS_VehicleType" IsForeignKey="true" />
      <Association Name="LS_Route_AC_PPCWhiteList" Member="LS_Route" ThisKey="RouteID" OtherKey="RouteID" Type="LS_Route" IsForeignKey="true" />
      <Association Name="LS_Lane_AC_PPCWhiteList" Member="LS_Lane1" ThisKey="LaneIDIn" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Lane_AC_PPCWhiteList1" Member="LS_Lane" ThisKey="LaneIDOut" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Station_AC_PPCWhiteList" Member="LS_Station1" ThisKey="StationIDIn" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Station_AC_PPCWhiteList1" Member="LS_Station" ThisKey="StationIDOut" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Employee_AC_PPCWhiteList" Member="LS_Employee1" ThisKey="LockEmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
      <Association Name="LS_Employee_AC_PPCWhiteList1" Member="LS_Employee" ThisKey="UnlockEmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LS_Card" Member="LS_Cards">
    <Type Name="LS_Card">
      <Column Name="CardTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ProductTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CardTypeCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AC_TollWhiteList" Member="AC_TollWhiteLists">
    <Type Name="AC_TollWhiteList">
      <Column Name="ID" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="CardID" Type="System.String" DbType="VarChar(20) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VehicleTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FormatID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="VehiclePlateIn" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StationIDIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneIDIn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastCheckDateIn" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="VehiclePlateOut" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="StationIDOut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LaneIDOut" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastCheckDateOut" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="RouteID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsLock" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockEmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LockDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UnlockEmployeeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UnlockDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsLost" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="ImageIDIn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ImageIDOut" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="LS_VehicleType_AC_TollWhiteList" Member="LS_VehicleType" ThisKey="VehicleTypeID" OtherKey="VehicleTypeID" Type="LS_VehicleType" IsForeignKey="true" />
      <Association Name="LS_Route_AC_TollWhiteList" Member="LS_Route" ThisKey="RouteID" OtherKey="RouteID" Type="LS_Route" IsForeignKey="true" />
      <Association Name="LS_Lane_AC_TollWhiteList" Member="LS_Lane1" ThisKey="LaneIDIn" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Lane_AC_TollWhiteList1" Member="LS_Lane" ThisKey="LaneIDOut" OtherKey="LaneID" Type="LS_Lane" IsForeignKey="true" />
      <Association Name="LS_Station_AC_TollWhiteList" Member="LS_Station1" ThisKey="StationIDIn" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Station_AC_TollWhiteList1" Member="LS_Station" ThisKey="LaneIDOut" OtherKey="StationID" Type="LS_Station" IsForeignKey="true" />
      <Association Name="LS_Employee_AC_TollWhiteList" Member="LS_Employee1" ThisKey="LockEmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
      <Association Name="LS_Employee_AC_TollWhiteList1" Member="LS_Employee" ThisKey="UnlockEmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LS_Employee" Member="LS_Employees">
    <Type Name="LS_Employee">
      <Column Name="EmployeeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EmployeeCode" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="PositionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="TeamID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IDNo" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ManagerID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="UserName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="IsUsed" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="IsTeamLeader" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="SmartCardID" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Association Name="LS_Employee_IN_CheckSmartCard" Member="IN_CheckSmartCards" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="IN_CheckSmartCard" />
      <Association Name="LS_Employee_OUT_CheckSmartCard" Member="OUT_CheckSmartCards" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="OUT_CheckSmartCard" />
      <Association Name="LS_Employee_AC_PPCWhiteList" Member="AC_PPCWhiteLists1" ThisKey="EmployeeID" OtherKey="LockEmployeeID" Type="AC_PPCWhiteList" />
      <Association Name="LS_Employee_AC_PPCWhiteList1" Member="AC_PPCWhiteLists" ThisKey="EmployeeID" OtherKey="UnlockEmployeeID" Type="AC_PPCWhiteList" />
      <Association Name="LS_Employee_AC_TollWhiteList" Member="AC_TollWhiteLists1" ThisKey="EmployeeID" OtherKey="LockEmployeeID" Type="AC_TollWhiteList" />
      <Association Name="LS_Employee_AC_TollWhiteList1" Member="AC_TollWhiteLists" ThisKey="EmployeeID" OtherKey="UnlockEmployeeID" Type="AC_TollWhiteList" />
      <Association Name="LS_Employee_LS_Employee" Member="LS_Employee2" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="LS_Employee" Cardinality="One" />
      <Association Name="LS_Employee_LS_Employee" Member="LS_Employee1" ThisKey="EmployeeID" OtherKey="EmployeeID" Type="LS_Employee" IsForeignKey="true" />
    </Type>
  </Table>
</Database>