#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="HPE")]
	public partial class QLHPDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLS_VehicleType(LS_VehicleType instance);
    partial void UpdateLS_VehicleType(LS_VehicleType instance);
    partial void DeleteLS_VehicleType(LS_VehicleType instance);
    partial void InsertAC_PPCWhiteList(AC_PPCWhiteList instance);
    partial void UpdateAC_PPCWhiteList(AC_PPCWhiteList instance);
    partial void DeleteAC_PPCWhiteList(AC_PPCWhiteList instance);
    #endregion
		
		public QLHPDataContext() : 
				base(global::TollTicketManagement.Properties.Settings.Default.HPEConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLHPDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LS_VehicleType> LS_VehicleTypes
		{
			get
			{
				return this.GetTable<LS_VehicleType>();
			}
		}
		
		public System.Data.Linq.Table<AC_PPCWhiteList> AC_PPCWhiteLists
		{
			get
			{
				return this.GetTable<AC_PPCWhiteList>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LS_VehicleType")]
	public partial class LS_VehicleType : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _VehicleTypeID;
		
		private string _VehicleTypeCode;
		
		private string _Name;
		
		private string _ShortName;
		
		private System.Nullable<int> _AmountPerKm;
		
		private string _Note;
		
		private bool _IsUsed;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnVehicleTypeIDChanging(int value);
    partial void OnVehicleTypeIDChanged();
    partial void OnVehicleTypeCodeChanging(string value);
    partial void OnVehicleTypeCodeChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnShortNameChanging(string value);
    partial void OnShortNameChanged();
    partial void OnAmountPerKmChanging(System.Nullable<int> value);
    partial void OnAmountPerKmChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    partial void OnIsUsedChanging(bool value);
    partial void OnIsUsedChanged();
    #endregion
		
		public LS_VehicleType()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeCode", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string VehicleTypeCode
		{
			get
			{
				return this._VehicleTypeCode;
			}
			set
			{
				if ((this._VehicleTypeCode != value))
				{
					this.OnVehicleTypeCodeChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeCode = value;
					this.SendPropertyChanged("VehicleTypeCode");
					this.OnVehicleTypeCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortName", DbType="NVarChar(200)")]
		public string ShortName
		{
			get
			{
				return this._ShortName;
			}
			set
			{
				if ((this._ShortName != value))
				{
					this.OnShortNameChanging(value);
					this.SendPropertyChanging();
					this._ShortName = value;
					this.SendPropertyChanged("ShortName");
					this.OnShortNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AmountPerKm", DbType="Int")]
		public System.Nullable<int> AmountPerKm
		{
			get
			{
				return this._AmountPerKm;
			}
			set
			{
				if ((this._AmountPerKm != value))
				{
					this.OnAmountPerKmChanging(value);
					this.SendPropertyChanging();
					this._AmountPerKm = value;
					this.SendPropertyChanged("AmountPerKm");
					this.OnAmountPerKmChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(500)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUsed", DbType="Bit NOT NULL")]
		public bool IsUsed
		{
			get
			{
				return this._IsUsed;
			}
			set
			{
				if ((this._IsUsed != value))
				{
					this.OnIsUsedChanging(value);
					this.SendPropertyChanging();
					this._IsUsed = value;
					this.SendPropertyChanged("IsUsed");
					this.OnIsUsedChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AC_PPCWhiteList")]
	public partial class AC_PPCWhiteList : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Guid _ID;
		
		private string _CardID;
		
		private System.Nullable<int> _VehicleTypeID;
		
		private string _FormatID;
		
		private System.Nullable<int> _StationIDIn;
		
		private System.Nullable<int> _LaneIDIn;
		
		private System.Nullable<System.DateTime> _LastCheckDateIn;
		
		private System.Nullable<int> _StationIDOut;
		
		private System.Nullable<int> _LaneIDOut;
		
		private System.Nullable<System.DateTime> _LastCheckDateOut;
		
		private System.Nullable<int> _RouteID;
		
		private System.Nullable<int> _Hour;
		
		private System.Nullable<int> _Day;
		
		private System.Nullable<int> _Month;
		
		private System.Nullable<int> _Year;
		
		private System.Nullable<bool> _IsUsed;
		
		private string _Note;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(System.Guid value);
    partial void OnIDChanged();
    partial void OnCardIDChanging(string value);
    partial void OnCardIDChanged();
    partial void OnVehicleTypeIDChanging(System.Nullable<int> value);
    partial void OnVehicleTypeIDChanged();
    partial void OnFormatIDChanging(string value);
    partial void OnFormatIDChanged();
    partial void OnStationIDInChanging(System.Nullable<int> value);
    partial void OnStationIDInChanged();
    partial void OnLaneIDInChanging(System.Nullable<int> value);
    partial void OnLaneIDInChanged();
    partial void OnLastCheckDateInChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckDateInChanged();
    partial void OnStationIDOutChanging(System.Nullable<int> value);
    partial void OnStationIDOutChanged();
    partial void OnLaneIDOutChanging(System.Nullable<int> value);
    partial void OnLaneIDOutChanged();
    partial void OnLastCheckDateOutChanging(System.Nullable<System.DateTime> value);
    partial void OnLastCheckDateOutChanged();
    partial void OnRouteIDChanging(System.Nullable<int> value);
    partial void OnRouteIDChanged();
    partial void OnHourChanging(System.Nullable<int> value);
    partial void OnHourChanged();
    partial void OnDayChanging(System.Nullable<int> value);
    partial void OnDayChanged();
    partial void OnMonthChanging(System.Nullable<int> value);
    partial void OnMonthChanged();
    partial void OnYearChanging(System.Nullable<int> value);
    partial void OnYearChanged();
    partial void OnIsUsedChanging(System.Nullable<bool> value);
    partial void OnIsUsedChanged();
    partial void OnNoteChanging(string value);
    partial void OnNoteChanged();
    #endregion
		
		public AC_PPCWhiteList()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CardID", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CardID
		{
			get
			{
				return this._CardID;
			}
			set
			{
				if ((this._CardID != value))
				{
					this.OnCardIDChanging(value);
					this.SendPropertyChanging();
					this._CardID = value;
					this.SendPropertyChanged("CardID");
					this.OnCardIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VehicleTypeID", DbType="Int")]
		public System.Nullable<int> VehicleTypeID
		{
			get
			{
				return this._VehicleTypeID;
			}
			set
			{
				if ((this._VehicleTypeID != value))
				{
					this.OnVehicleTypeIDChanging(value);
					this.SendPropertyChanging();
					this._VehicleTypeID = value;
					this.SendPropertyChanged("VehicleTypeID");
					this.OnVehicleTypeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FormatID", DbType="VarChar(20)")]
		public string FormatID
		{
			get
			{
				return this._FormatID;
			}
			set
			{
				if ((this._FormatID != value))
				{
					this.OnFormatIDChanging(value);
					this.SendPropertyChanging();
					this._FormatID = value;
					this.SendPropertyChanged("FormatID");
					this.OnFormatIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDIn", DbType="Int")]
		public System.Nullable<int> StationIDIn
		{
			get
			{
				return this._StationIDIn;
			}
			set
			{
				if ((this._StationIDIn != value))
				{
					this.OnStationIDInChanging(value);
					this.SendPropertyChanging();
					this._StationIDIn = value;
					this.SendPropertyChanged("StationIDIn");
					this.OnStationIDInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDIn", DbType="Int")]
		public System.Nullable<int> LaneIDIn
		{
			get
			{
				return this._LaneIDIn;
			}
			set
			{
				if ((this._LaneIDIn != value))
				{
					this.OnLaneIDInChanging(value);
					this.SendPropertyChanging();
					this._LaneIDIn = value;
					this.SendPropertyChanged("LaneIDIn");
					this.OnLaneIDInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateIn", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateIn
		{
			get
			{
				return this._LastCheckDateIn;
			}
			set
			{
				if ((this._LastCheckDateIn != value))
				{
					this.OnLastCheckDateInChanging(value);
					this.SendPropertyChanging();
					this._LastCheckDateIn = value;
					this.SendPropertyChanged("LastCheckDateIn");
					this.OnLastCheckDateInChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StationIDOut", DbType="Int")]
		public System.Nullable<int> StationIDOut
		{
			get
			{
				return this._StationIDOut;
			}
			set
			{
				if ((this._StationIDOut != value))
				{
					this.OnStationIDOutChanging(value);
					this.SendPropertyChanging();
					this._StationIDOut = value;
					this.SendPropertyChanged("StationIDOut");
					this.OnStationIDOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LaneIDOut", DbType="Int")]
		public System.Nullable<int> LaneIDOut
		{
			get
			{
				return this._LaneIDOut;
			}
			set
			{
				if ((this._LaneIDOut != value))
				{
					this.OnLaneIDOutChanging(value);
					this.SendPropertyChanging();
					this._LaneIDOut = value;
					this.SendPropertyChanged("LaneIDOut");
					this.OnLaneIDOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LastCheckDateOut", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastCheckDateOut
		{
			get
			{
				return this._LastCheckDateOut;
			}
			set
			{
				if ((this._LastCheckDateOut != value))
				{
					this.OnLastCheckDateOutChanging(value);
					this.SendPropertyChanging();
					this._LastCheckDateOut = value;
					this.SendPropertyChanged("LastCheckDateOut");
					this.OnLastCheckDateOutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RouteID", DbType="Int")]
		public System.Nullable<int> RouteID
		{
			get
			{
				return this._RouteID;
			}
			set
			{
				if ((this._RouteID != value))
				{
					this.OnRouteIDChanging(value);
					this.SendPropertyChanging();
					this._RouteID = value;
					this.SendPropertyChanged("RouteID");
					this.OnRouteIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hour", DbType="Int")]
		public System.Nullable<int> Hour
		{
			get
			{
				return this._Hour;
			}
			set
			{
				if ((this._Hour != value))
				{
					this.OnHourChanging(value);
					this.SendPropertyChanging();
					this._Hour = value;
					this.SendPropertyChanged("Hour");
					this.OnHourChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Day", DbType="Int")]
		public System.Nullable<int> Day
		{
			get
			{
				return this._Day;
			}
			set
			{
				if ((this._Day != value))
				{
					this.OnDayChanging(value);
					this.SendPropertyChanging();
					this._Day = value;
					this.SendPropertyChanged("Day");
					this.OnDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Month", DbType="Int")]
		public System.Nullable<int> Month
		{
			get
			{
				return this._Month;
			}
			set
			{
				if ((this._Month != value))
				{
					this.OnMonthChanging(value);
					this.SendPropertyChanging();
					this._Month = value;
					this.SendPropertyChanged("Month");
					this.OnMonthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Year", DbType="Int")]
		public System.Nullable<int> Year
		{
			get
			{
				return this._Year;
			}
			set
			{
				if ((this._Year != value))
				{
					this.OnYearChanging(value);
					this.SendPropertyChanging();
					this._Year = value;
					this.SendPropertyChanged("Year");
					this.OnYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsUsed", DbType="Bit")]
		public System.Nullable<bool> IsUsed
		{
			get
			{
				return this._IsUsed;
			}
			set
			{
				if ((this._IsUsed != value))
				{
					this.OnIsUsedChanging(value);
					this.SendPropertyChanging();
					this._IsUsed = value;
					this.SendPropertyChanged("IsUsed");
					this.OnIsUsedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Note", DbType="NVarChar(200)")]
		public string Note
		{
			get
			{
				return this._Note;
			}
			set
			{
				if ((this._Note != value))
				{
					this.OnNoteChanging(value);
					this.SendPropertyChanging();
					this._Note = value;
					this.SendPropertyChanged("Note");
					this.OnNoteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
