//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_ListVehicleInfomationInOut
    {
        public string codedevide { get; set; }
        public Nullable<System.Guid> InCheckID { get; set; }
        public Nullable<System.DateTime> DateIn { get; set; }
        public string VehicelTypeNameIn { get; set; }
        public string NumberRecogIn { get; set; }
        public string NameEmloyeeIn { get; set; }
        public string TypeDevideIn { get; set; }
        public string StationNameIn { get; set; }
        public string LaneIn { get; set; }
        public string ShiftIDin { get; set; }
        public string ImageIDIn { get; set; }
        public Nullable<int> PriceIn { get; set; }
        public Nullable<System.Guid> OutCheckID { get; set; }
        public Nullable<System.DateTime> DateOut { get; set; }
        public string VehicleTypeNameOut { get; set; }
        public string NumberRecogOut { get; set; }
        public string NameEmployeeOut { get; set; }
        public string TypeDevideOut { get; set; }
        public string StationNameOut { get; set; }
        public string LaneOut { get; set; }
        public string ShiftIDOut { get; set; }
        public string ImageIDOut { get; set; }
        public Nullable<int> PriceOut { get; set; }
        public Nullable<int> ChargeAmount { get; set; }
        public string RouteNameIn { get; set; }
        public string RouteNameOut { get; set; }
        public int TableName { get; set; }
        public string LaneNameIn { get; set; }
        public string LaneNameOut { get; set; }
        public Nullable<int> VehicleTypeIDIn { get; set; }
        public Nullable<int> VehicleTypeIDOut { get; set; }
    }
}
