//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_RPT_VehicleLane_Btc
    {
        public Nullable<long> No { get; set; }
        public System.Guid ID { get; set; }
        public System.DateTime Date { get; set; }
        public System.DateTime hour { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> LaneID { get; set; }
        public string StationName { get; set; }
        public string ImageID { get; set; }
        public string RecogPlateNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
    }
}
