//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_SearchVehicleDetail
    {
        public System.Guid HistoryMarkErrorID { get; set; }
        public string TableName { get; set; }
        public int Sequence { get; set; }
        public System.Guid InCheckTicketID { get; set; }
        public bool IsPrecheck { get; set; }
        public Nullable<short> SupervisionStatus { get; set; }
        public Nullable<int> ErrorID { get; set; }
        public int EmployeePostCheck { get; set; }
        public System.DateTime MarkDate { get; set; }
        public Nullable<bool> IsStationManager { get; set; }
        public string Note { get; set; }
        public System.DateTime CheckDate { get; set; }
        public string RecogPlateNumber { get; set; }
        public System.DateTime CheckDateGroup { get; set; }
        public Nullable<int> StationID { get; set; }
        public Nullable<int> LaneID { get; set; }
        public Nullable<int> ShiftID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string Counter { get; set; }
        public string CodeVehicle { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public string ImageID { get; set; }
        public Nullable<int> ErrorIDTest { get; set; }
        public Nullable<short> PrecheckStatus { get; set; }
        public System.Guid InCheckForceOpenID { get; set; }
        public string RouteName { get; set; }
        public System.Guid InCheckForceOpenGroupID { get; set; }
    }
}
