//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_Search_VehicleInformation
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string RegisPlateNumber { get; set; }
        public string AreaCode { get; set; }
        public int VehicleTypeID { get; set; }
        public Nullable<int> TicketTypeID { get; set; }
        public Nullable<int> Amount { get; set; }
        public System.DateTime RegisDate { get; set; }
        public string Owners { get; set; }
        public string Address { get; set; }
        public Nullable<int> Seats { get; set; }
        public Nullable<int> VehicleLoad { get; set; }
        public Nullable<int> TRLgMooc { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string NickName { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
    }
}
