//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_SearchDeviceResult
    {
        public int STT { get; set; }
        public string AccountID { get; set; }
        public string TicketType { get; set; }
        public Nullable<int> Balance { get; set; }
        public string Status { get; set; }
        public int TableType { get; set; }
        public Nullable<short> StatusCode { get; set; }
    }
}
