//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_Search_EmployeeCounter
    {
        public System.Guid HistoryMarkErrorID { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> StationID { get; set; }
        public System.Guid InCheckTicketID { get; set; }
        public bool IsPrecheck { get; set; }
        public Nullable<short> SupervisionStatus { get; set; }
        public Nullable<int> ErrorID { get; set; }
        public int EmployeeID { get; set; }
        public int ShiftID { get; set; }
        public System.DateTime MarkDate { get; set; }
        public Nullable<bool> IsStationManager { get; set; }
        public string Note { get; set; }
    }
}
