//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_RPT_Quantity_SmartCard
    {
        public short Lane_type { get; set; }
        public string Name_Lane { get; set; }
        public string Name_goodstype { get; set; }
        public string Goods { get; set; }
        public string Name_Amount { get; set; }
        public int Amount { get; set; }
        public string Lane_code { get; set; }
    }
}
