//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_RPT_Traffic_Base
    {
        public string Name { get; set; }
        public string PriceName { get; set; }
        public int Price { get; set; }
        public string LaneName { get; set; }
        public int PriceSumLane { get; set; }
    }
}
