//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_RPT_Traffic
    {
        public string Price { get; set; }
        public int Lane1 { get; set; }
        public int Lane2 { get; set; }
        public int Lane3 { get; set; }
        public int Lane4 { get; set; }
        public int Lane5 { get; set; }
        public int Lane6 { get; set; }
        public int Lane7 { get; set; }
        public int Lane8 { get; set; }
        public int Lane9 { get; set; }
        public int Lane10 { get; set; }
        public int Lane11 { get; set; }
        public int Lane12 { get; set; }
        public int SumLane { get; set; }
        public int PriceSumLane { get; set; }
    }
}
