//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUP_IsforceGroupDetail
    {
        public Nullable<short> SupervisionStatus { get; set; }
        public Nullable<int> ErrorID { get; set; }
        public string Note { get; set; }
        public System.DateTime CheckDate { get; set; }
        public string RecogPlateNumber { get; set; }
        public Nullable<short> PrecheckStatus { get; set; }
        public System.Guid ID { get; set; }
    }
}
