//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AC_PPCWhiteList
    {
        public System.Guid ID { get; set; }
        public string CardID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public string FormatID { get; set; }
        public string VehiclePlateIn { get; set; }
        public Nullable<int> StationIDIn { get; set; }
        public Nullable<int> LaneIDIn { get; set; }
        public Nullable<System.DateTime> LastCheckDateIn { get; set; }
        public string VehiclePlateOut { get; set; }
        public Nullable<int> StationIDOut { get; set; }
        public Nullable<int> LaneIDOut { get; set; }
        public Nullable<System.DateTime> LastCheckDateOut { get; set; }
        public Nullable<int> RouteID { get; set; }
        public Nullable<int> Hour { get; set; }
        public Nullable<int> Day { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<int> LockEmployeeID { get; set; }
        public Nullable<System.DateTime> LockDate { get; set; }
        public Nullable<int> UnlockEmployeeID { get; set; }
        public Nullable<System.DateTime> UnlockDate { get; set; }
        public Nullable<bool> IsLost { get; set; }
        public string Note { get; set; }
        public string TransactionIDIn { get; set; }
        public string TransactionIDOut { get; set; }
        public string ImageIDIn { get; set; }
    }
}
