//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_Lane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LS_Lane()
        {
            this.IN_CheckSmartCard = new HashSet<IN_CheckSmartCard>();
            this.OUT_CheckPrepaidCard = new HashSet<OUT_CheckPrepaidCard>();
            this.OUT_CheckSmartCard = new HashSet<OUT_CheckSmartCard>();
        }
    
        public int LaneID { get; set; }
        public int StationID { get; set; }
        public string LaneCode { get; set; }
        public string Name { get; set; }
        public short DirectionType { get; set; }
        public int LaneType { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_CheckSmartCard> IN_CheckSmartCard { get; set; }
        public virtual LS_Station LS_Station { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUT_CheckPrepaidCard> OUT_CheckPrepaidCard { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OUT_CheckSmartCard> OUT_CheckSmartCard { get; set; }
    }
}
