//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollManagement.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class LS_VehicleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LS_VehicleType()
        {
            this.IN_CheckSmartCard = new HashSet<IN_CheckSmartCard>();
        }
    
        public int VehicleTypeID { get; set; }
        public string VehicleTypeCode { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public Nullable<int> AmountPerKm { get; set; }
        public string Note { get; set; }
        public bool IsUsed { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IN_CheckSmartCard> IN_CheckSmartCard { get; set; }
    }
}
