//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollManagement.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HPEEntities1 : DbContext
    {
        public HPEEntities1()
            : base("name=HPEEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AC_PPCWhiteList> AC_PPCWhiteList { get; set; }
        public virtual DbSet<AC_TollWhiteList> AC_TollWhiteList { get; set; }
        public virtual DbSet<IN_CheckPrepaidCard> IN_CheckPrepaidCard { get; set; }
        public virtual DbSet<IN_CheckSmartCard> IN_CheckSmartCard { get; set; }
        public virtual DbSet<LS_Lane> LS_Lane { get; set; }
        public virtual DbSet<LS_Route> LS_Route { get; set; }
        public virtual DbSet<LS_Station> LS_Station { get; set; }
        public virtual DbSet<LS_VehicleType> LS_VehicleType { get; set; }
        public virtual DbSet<OUT_CheckPrepaidCard> OUT_CheckPrepaidCard { get; set; }
        public virtual DbSet<OUT_CheckSmartCard> OUT_CheckSmartCard { get; set; }
    
        public virtual ObjectResult<f_sp_IN_CheckSmartCard_GetByCardIDAndSortTransactionID_Result> f_sp_IN_CheckSmartCard_GetByCardIDAndSortTransactionID(string cardID, string transactionID)
        {
            var cardIDParameter = cardID != null ?
                new ObjectParameter("CardID", cardID) :
                new ObjectParameter("CardID", typeof(string));
    
            var transactionIDParameter = transactionID != null ?
                new ObjectParameter("TransactionID", transactionID) :
                new ObjectParameter("TransactionID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<f_sp_IN_CheckSmartCard_GetByCardIDAndSortTransactionID_Result>("f_sp_IN_CheckSmartCard_GetByCardIDAndSortTransactionID", cardIDParameter, transactionIDParameter);
        }
    
        public virtual ObjectResult<TKCardSuDung_Result> TKCardSuDung(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKCardSuDung_Result>("TKCardSuDung", monthParameter, yearParameter);
        }
    
        public virtual ObjectResult<TKCardSuDung1_Result> TKCardSuDung1(Nullable<int> month, Nullable<int> year)
        {
            var monthParameter = month.HasValue ?
                new ObjectParameter("Month", month) :
                new ObjectParameter("Month", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("Year", year) :
                new ObjectParameter("Year", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TKCardSuDung1_Result>("TKCardSuDung1", monthParameter, yearParameter);
        }
    }
}
