//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Resources.Message
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        public static string DeviceName1;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITD.CTS.Supervision.HDLE_UI.Resources.Message.CommonMessage", typeof(CommonMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối bị lỗi.
        /// </summary>
        internal static string ConDBError {
            get {
                return ResourceManager.GetString("ConDBError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kết nối thành công.
        /// </summary>
        internal static string ConDBSuccess {
            get {
                return ResourceManager.GetString("ConDBSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hệ thống bị mất kết nối, xin vui lòng kiểm tra lại đường truyền !.
        /// </summary>
        internal static string LS_ALL_Disconnect {
            get {
                return ResourceManager.GetString("LS_ALL_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tỉnh thành này đã tồn tại, xin vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_AreaEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_AreaEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tỉnh thành phải là số có 3 ký tự.
        /// </summary>
        internal static string LS_AreaEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_AreaEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tỉnh thành phải là số.
        /// </summary>
        internal static string LS_AreaEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_AreaEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS_AreaEditView_ErrorTitle.
        /// </summary>
        internal static string LS_AreaEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_AreaEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập mã tỉnh thành.
        /// </summary>
        internal static string LS_AreaEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_AreaEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập tên tỉnh thành.
        /// </summary>
        internal static string LS_AreaEditView_NullName {
            get {
                return ResourceManager.GetString("LS_AreaEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ đặc biệt này đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_CardSpecialEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ đặc biệt là số có 2 ký tự.
        /// </summary>
        internal static string LS_CardSpecialEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã thẻ đặc biệt phải là số.
        /// </summary>
        internal static string LS_CardSpecialEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại...
        /// </summary>
        internal static string LS_CardSpecialEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã thẻ đặc biệt.
        /// </summary>
        internal static string LS_CardSpecialEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên thẻ đặc biệt.
        /// </summary>
        internal static string LS_CardSpecialEditView_NullName {
            get {
                return ResourceManager.GetString("LS_CardSpecialEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo .
        /// </summary>
        internal static string LS_Company_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Company_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 3 kí tự !.
        /// </summary>
        internal static string LS_CompanyBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_CompanyBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Công ty đã có !.
        /// </summary>
        internal static string LS_CompanyBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_CompanyBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống  !.
        /// </summary>
        internal static string LS_CompanyBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_CompanyBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải là số  !.
        /// </summary>
        internal static string LS_CompanyBarcodeNotNum {
            get {
                return ResourceManager.GetString("LS_CompanyBarcodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng Email  !.
        /// </summary>
        internal static string LS_CompanyEmailFormat {
            get {
                return ResourceManager.GetString("LS_CompanyEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Fax phải lớn hơn hoặc bằng 6 và nhỏ hơn 11 kí tự !.
        /// </summary>
        internal static string LS_CompanyFaxFormat {
            get {
                return ResourceManager.GetString("LS_CompanyFaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Công ty này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_CompanyIsUsed {
            get {
                return ResourceManager.GetString("LS_CompanyIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống  !.
        /// </summary>
        internal static string LS_CompanyNameNotNull {
            get {
                return ResourceManager.GetString("LS_CompanyNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải lớn hoặc bằng 6 và nhỏ hơn 11 kí tự  !.
        /// </summary>
        internal static string LS_CompanyPhoneFormat {
            get {
                return ResourceManager.GetString("LS_CompanyPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế này đã có !.
        /// </summary>
        internal static string LS_CompanyTaxCodeIsHad {
            get {
                return ResourceManager.GetString("LS_CompanyTaxCodeIsHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế phải lớn hơn hoặc bằng 10 và nhỏ hơn hoăc bằng 14 kí tự !.
        /// </summary>
        internal static string LS_CompanyTaxFormat {
            get {
                return ResourceManager.GetString("LS_CompanyTaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng Website , VD: http://www.vanlanguni.edu.vn !.
        /// </summary>
        internal static string LS_CompanyWebsiteFormat {
            get {
                return ResourceManager.GetString("LS_CompanyWebsiteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website không được có khoảng trắng !.
        /// </summary>
        internal static string LS_CompanyWebsiteNoWhileSpace {
            get {
                return ResourceManager.GetString("LS_CompanyWebsiteNoWhileSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Currency_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Currency_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 2 kí tự !.
        /// </summary>
        internal static string LS_CurrencyBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_CurrencyBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã iền tệ đã có !.
        /// </summary>
        internal static string LS_CurrencyBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_CurrencyBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_CurrencyBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_CurrencyBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải là số !.
        /// </summary>
        internal static string LS_CurrencyBarcodeNotNum {
            get {
                return ResourceManager.GetString("LS_CurrencyBarcodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiền tệ này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_CurrencyIsUsed {
            get {
                return ResourceManager.GetString("LS_CurrencyIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_CurrencyNameNotNull {
            get {
                return ResourceManager.GetString("LS_CurrencyNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Customer_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Customer_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ không được để trống !.
        /// </summary>
        internal static string LS_CustomerAddressNotNull {
            get {
                return ResourceManager.GetString("LS_CustomerAddressNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 6 kí tự !.
        /// </summary>
        internal static string LS_CustomerBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_CustomerBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã khách hàng đã có !.
        /// </summary>
        internal static string LS_CustomerBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_CustomerBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_CustomerBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_CustomerBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải là số !.
        /// </summary>
        internal static string LS_CustomerBarcodeNotNum {
            get {
                return ResourceManager.GetString("LS_CustomerBarcodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên công ty không được để trống !.
        /// </summary>
        internal static string LS_CustomerCompanyNameNotNull {
            get {
                return ResourceManager.GetString("LS_CustomerCompanyNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không đúng định dạng Email !.
        /// </summary>
        internal static string LS_CustomerEmailFormat {
            get {
                return ResourceManager.GetString("LS_CustomerEmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Khách hàng này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_CustomerIsUsed {
            get {
                return ResourceManager.GetString("LS_CustomerIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_CustomerNameNotNull {
            get {
                return ResourceManager.GetString("LS_CustomerNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải 10 hoặc 11 kí tự !.
        /// </summary>
        internal static string LS_CustomerPhoneFormat {
            get {
                return ResourceManager.GetString("LS_CustomerPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Xoá không thành công.
        /// </summary>
        internal static string LS_DeleteAll {
            get {
                return ResourceManager.GetString("LS_DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_EmployeeEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên 4 ký tự, tự phát sinh không cho phép chỉnh sửa.
        /// </summary>
        internal static string LS_EmployeeEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên phải là số.
        /// </summary>
        internal static string LS_EmployeeEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email không đúng định dạng.
        /// </summary>
        internal static string LS_EmployeeEditView_EmailNotValid {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã có tổ trưởng.
        /// </summary>
        internal static string LS_EmployeeEditView_ErrorIsTeamLeader {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_ErrorIsTeamLeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Đã đủ số nhân viên trong tổ.
        /// </summary>
        internal static string LS_EmployeeEditView_ErrorTeam {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_ErrorTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại các thông tin sau của nhân viên.
        /// </summary>
        internal static string LS_EmployeeEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND đã tồn tại rồi.
        /// </summary>
        internal static string LS_EmployeeEditView_IDNoExists {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_IDNoExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số CMND phải là số.
        /// </summary>
        internal static string LS_EmployeeEditView_IDNoNotNum {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_IDNoNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải là số.
        /// </summary>
        internal static string LS_EmployeeEditView_MobileNotNum {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_MobileNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập mã nhân viên.
        /// </summary>
        internal static string LS_EmployeeEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập số CMND.
        /// </summary>
        internal static string LS_EmployeeEditView_NullIDNo {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_NullIDNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập tên nhân viên.
        /// </summary>
        internal static string LS_EmployeeEditView_NullName {
            get {
                return ResourceManager.GetString("LS_EmployeeEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Lane_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Lane_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã làn này đã có !.
        /// </summary>
        internal static string LS_LaneCodeIsHad {
            get {
                return ResourceManager.GetString("LS_LaneCodeIsHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã làn phải đủ 4 kí tự !.
        /// </summary>
        internal static string LS_LaneCodeNotFormat {
            get {
                return ResourceManager.GetString("LS_LaneCodeNotFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Làn xe này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_LaneIsUsed {
            get {
                return ResourceManager.GetString("LS_LaneIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_LaneNameNotNull {
            get {
                return ResourceManager.GetString("LS_LaneNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Position_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Position_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 3 kí tự !.
        /// </summary>
        internal static string LS_PositionBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_PositionBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã chức vụ đã có !.
        /// </summary>
        internal static string LS_PositionBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_PositionBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_PositionBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_PositionBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chức vụ này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_PositionIsUsed {
            get {
                return ResourceManager.GetString("LS_PositionIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_PositionNameNotNull {
            get {
                return ResourceManager.GetString("LS_PositionNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_ProductType_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_ProductType_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 4 kí tự !.
        /// </summary>
        internal static string LS_ProductTypeBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_ProductTypeBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã Loại đã có !.
        /// </summary>
        internal static string LS_ProductTypeBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_ProductTypeBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_ProductTypeBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_ProductTypeBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loại thiết bị này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_ProductTypeIsUsed {
            get {
                return ResourceManager.GetString("LS_ProductTypeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_ProductTypeNameNotNull {
            get {
                return ResourceManager.GetString("LS_ProductTypeNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Report_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Report_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dữ liệu trong danh sách không có !.
        /// </summary>
        internal static string LS_Report_Message {
            get {
                return ResourceManager.GetString("LS_Report_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Route_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Route_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm đi phải khác trạm đến !.
        /// </summary>
        internal static string LS_Route_NoChooseSameRoute {
            get {
                return ResourceManager.GetString("LS_Route_NoChooseSameRoute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình này đã có !.
        /// </summary>
        internal static string LS_RouteBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_RouteBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lộ trình bị này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_RouteIsUsed {
            get {
                return ResourceManager.GetString("LS_RouteIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_RouteNameNotNull {
            get {
                return ResourceManager.GetString("LS_RouteNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Shift_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Shift_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 3 kí tự !.
        /// </summary>
        internal static string LS_ShiftBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_ShiftBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã ca đã có !.
        /// </summary>
        internal static string LS_ShiftBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_ShiftBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_ShiftBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_ShiftBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_ShiftIsUsed {
            get {
                return ResourceManager.GetString("LS_ShiftIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_ShiftNameNotNull {
            get {
                return ResourceManager.GetString("LS_ShiftNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giờ ra ca phải lớn hơn giờ vào ca !.
        /// </summary>
        internal static string LS_ShiftTimeError {
            get {
                return ResourceManager.GetString("LS_ShiftTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thời gian bắt đầu và kết thúc ca này đã có !.
        /// </summary>
        internal static string LS_ShiftTimeHad {
            get {
                return ResourceManager.GetString("LS_ShiftTimeHad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Station_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Station_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 2 kí tự !.
        /// </summary>
        internal static string LS_StationBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_StationBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_StationBarCodeNotNull {
            get {
                return ResourceManager.GetString("LS_StationBarCodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số Fax phải lớn hơn hoặc bằng 6 và nhỏ hơn 11 kí tự !.
        /// </summary>
        internal static string LS_StationFaxFormat {
            get {
                return ResourceManager.GetString("LS_StationFaxFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_StationIsUsed {
            get {
                return ResourceManager.GetString("LS_StationIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên phải có nhiều hơn 1 và tối đa là 50 kí tự !.
        /// </summary>
        internal static string LS_StationNameFormat {
            get {
                return ResourceManager.GetString("LS_StationNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_StationNameNotNull {
            get {
                return ResourceManager.GetString("LS_StationNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số điện thoại phải lớn hơn hoặc bằng 6 và nhỏ hơn 11 kí tự !.
        /// </summary>
        internal static string LS_StationPhoneFormat {
            get {
                return ResourceManager.GetString("LS_StationPhoneFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Stock_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Stock_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã kho đã có !.
        /// </summary>
        internal static string LS_StockBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_StockBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_StockBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_StockBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kho này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_StockIsUsed {
            get {
                return ResourceManager.GetString("LS_StockIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_StockNameNotNull {
            get {
                return ResourceManager.GetString("LS_StockNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo.
        /// </summary>
        internal static string LS_Team_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_Team_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã phải đúng 2 kí tự !.
        /// </summary>
        internal static string LS_TeamBarcodeFormat {
            get {
                return ResourceManager.GetString("LS_TeamBarcodeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã tổ đã có !.
        /// </summary>
        internal static string LS_TeamBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_TeamBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_TeamBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_TeamBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tổ này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_TeamIsUsed {
            get {
                return ResourceManager.GetString("LS_TeamIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng thành viên trong tổ không được để trống !.
        /// </summary>
        internal static string LS_TeamMemeberIsNull {
            get {
                return ResourceManager.GetString("LS_TeamMemeberIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_TeamNameNotNull {
            get {
                return ResourceManager.GetString("LS_TeamNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thông báo .
        /// </summary>
        internal static string LS_TeamStation_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_TeamStation_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm tổ này đã tồn tại !.
        /// </summary>
        internal static string LS_TeamStationBarcodeIsUsed {
            get {
                return ResourceManager.GetString("LS_TeamStationBarcodeIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã không được để trống !.
        /// </summary>
        internal static string LS_TeamStationBarcodeNotNull {
            get {
                return ResourceManager.GetString("LS_TeamStationBarcodeNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trạm tổ này đã được sử dụng, bạn không thể xoá !.
        /// </summary>
        internal static string LS_TeamStationIsUsed {
            get {
                return ResourceManager.GetString("LS_TeamStationIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tên không được để trống !.
        /// </summary>
        internal static string LS_TeamStationNameNotNull {
            get {
                return ResourceManager.GetString("LS_TeamStationNameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại vé này đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_TicketTypeEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại vé phải là số có 4 hoặc 5 chữ số.
        /// </summary>
        internal static string LS_TicketTypeEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại vé phải là số.
        /// </summary>
        internal static string LS_TicketTypeEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại các thông tin sau.
        /// </summary>
        internal static string LS_TicketTypeEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã vé.
        /// </summary>
        internal static string LS_TicketTypeEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên loại vé.
        /// </summary>
        internal static string LS_TicketTypeEditView_NullName {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn nhập giá vé không hợp lệ.
        /// </summary>
        internal static string LS_TicketTypeEditView_PriceNotValid {
            get {
                return ResourceManager.GetString("LS_TicketTypeEditView_PriceNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị tính đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_UnitEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_UnitEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị phải là số có 3 chữ số.
        /// </summary>
        internal static string LS_UnitEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_UnitEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã đơn vị phải là số.
        /// </summary>
        internal static string LS_UnitEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_UnitEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại các thông tin sau.
        /// </summary>
        internal static string LS_UnitEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_UnitEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã đơn vị.
        /// </summary>
        internal static string LS_UnitEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_UnitEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên đơn vị.
        /// </summary>
        internal static string LS_UnitEditView_NullName {
            get {
                return ResourceManager.GetString("LS_UnitEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Số lượng phải là số lớn hơn 0 và nhỏ hơn 1000.
        /// </summary>
        internal static string LS_UnitEditView_QuantityNotValid {
            get {
                return ResourceManager.GetString("LS_UnitEditView_QuantityNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại xe này đã được sử dụng, vui lòng nhập mã loại xe khác.
        /// </summary>
        internal static string LS_VehicleTypeEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại xe là số có 2 ký tự.
        /// </summary>
        internal static string LS_VehicleTypeEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã loại xe phải là số.
        /// </summary>
        internal static string LS_VehicleTypeEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại các thông tin sau.
        /// </summary>
        internal static string LS_VehicleTypeEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập mã loại xe.
        /// </summary>
        internal static string LS_VehicleTypeEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn chưa nhập tên loại xe.
        /// </summary>
        internal static string LS_VehicleTypeEditView_NullName {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giá tiền không được để trống, giá trị lớn hơn 0 và nhỏ hơn 100000.
        /// </summary>
        internal static string LS_VehicleTypeEditView_NullPrice {
            get {
                return ResourceManager.GetString("LS_VehicleTypeEditView_NullPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhà cung cấp đã tồn tại, vui lòng nhập mã khác.
        /// </summary>
        internal static string LS_VendorEditView_CodeDuplicate {
            get {
                return ResourceManager.GetString("LS_VendorEditView_CodeDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã công ty phải là số có 3 ký tự.
        /// </summary>
        internal static string LS_VendorEditView_CodeLength {
            get {
                return ResourceManager.GetString("LS_VendorEditView_CodeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã công ty phải là số.
        /// </summary>
        internal static string LS_VendorEditView_CodeNotNum {
            get {
                return ResourceManager.GetString("LS_VendorEditView_CodeNotNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng nhập email hợp lệ.
        /// </summary>
        internal static string LS_VendorEditView_EmailNotValid {
            get {
                return ResourceManager.GetString("LS_VendorEditView_EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng kiểm tra lại các thông tin sau.
        /// </summary>
        internal static string LS_VendorEditView_ErrorTitle {
            get {
                return ResourceManager.GetString("LS_VendorEditView_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax phải là số.
        /// </summary>
        internal static string LS_VendorEditView_FaxNotValid {
            get {
                return ResourceManager.GetString("LS_VendorEditView_FaxNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập mã công ty.
        /// </summary>
        internal static string LS_VendorEditView_NullCode {
            get {
                return ResourceManager.GetString("LS_VendorEditView_NullCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chưa nhập tên công ty.
        /// </summary>
        internal static string LS_VendorEditView_NullName {
            get {
                return ResourceManager.GetString("LS_VendorEditView_NullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Điện thoại phải là số.
        /// </summary>
        internal static string LS_VendorEditView_PhoneNotValid {
            get {
                return ResourceManager.GetString("LS_VendorEditView_PhoneNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã số thuế phải là số.
        /// </summary>
        internal static string LS_VendorEditView_TaxNotValid {
            get {
                return ResourceManager.GetString("LS_VendorEditView_TaxNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vui lòng chuẩn bị đầu đọc, SETUP CARD, KEY CARD.
        /// </summary>
        internal static string OBU_Prepare {
            get {
                return ResourceManager.GetString("OBU_Prepare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bạn vui lòng kiểm tra kết nối máy in.
        /// </summary>
        internal static string PrinterOfflineMsg {
            get {
                return ResourceManager.GetString("PrinterOfflineMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Không tìm thấy thiết bị. Vui lòng tìm trong danh sách đen.
        /// </summary>
        internal static string SUP_BlackList_PleaseSearch {
            get {
                return ResourceManager.GetString("SUP_BlackList_PleaseSearch", resourceCulture);
            }
        }
    }
}
