//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TollTicketManagement.Resources.Message
{
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormCode {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormCode() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ITD.CTS.Supervision.HDLE_UI.Resources.Message.FormCode", typeof(FormCode).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.01 - GIÁM SÁT HẬU KIỂM.
        /// </summary>
        public static string TOS_SUP_01 {
            get {
                return ResourceManager.GetString("TOS_SUP.01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.02 - ĐĂNG NHẬP.
        /// </summary>
        public static string TOS_SUP_02 {
            get {
                return ResourceManager.GetString("TOS_SUP.02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.03 - CẤU HÌNH HỆ THỐNG.
        /// </summary>
        public static string TOS_SUP_03 {
            get {
                return ResourceManager.GetString("TOS_SUP.03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.04 - QUẢN LÝ THÔNG TIN XE CHUẨN.
        /// </summary>
        public static string TOS_SUP_04 {
            get {
                return ResourceManager.GetString("TOS_SUP.04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.05 - CHỒNG HÌNH.
        /// </summary>
        public static string TOS_SUP_05 {
            get {
                return ResourceManager.GetString("TOS_SUP.05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.06 - GIÁM SÁT.
        /// </summary>
        public static string TOS_SUP_06 {
            get {
                return ResourceManager.GetString("TOS_SUP.06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.07 - HẬU KIỂM GIAO DỊCH THẺ.
        /// </summary>
        public static string TOS_SUP_07 {
            get {
                return ResourceManager.GetString("TOS_SUP.07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.08 - HẬU KIỂM GIAO DỊCH THẺ CHI TIẾT.
        /// </summary>
        public static string TOS_SUP_08 {
            get {
                return ResourceManager.GetString("TOS_SUP.08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.09 - HẬU KIỂM GIAO DỊCH THẺ TRẢ TRƯỚC.
        /// </summary>
        public static string TOS_SUP_09 {
            get {
                return ResourceManager.GetString("TOS_SUP.09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.10 - HẬU KIỂM GIAO DỊCH THẺ TRẢ TRƯỚC CHI TIẾT.
        /// </summary>
        public static string TOS_SUP_10 {
            get {
                return ResourceManager.GetString("TOS_SUP.10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.11 - HẬU KIỂM GIAO DỊCH THẺ THÁNG-QUÝ.
        /// </summary>
        public static string TOS_SUP_11 {
            get {
                return ResourceManager.GetString("TOS_SUP.11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.12 - HẬU KIỂM GIAO DỊCH THẺ THÁNG-QUÝ CHI TIẾT.
        /// </summary>
        public static string TOS_SUP_12 {
            get {
                return ResourceManager.GetString("TOS_SUP.12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.13 - HẬU KIỂM TẤT CẢ GIAO DỊCH.
        /// </summary>
        public static string TOS_SUP_13 {
            get {
                return ResourceManager.GetString("TOS_SUP.13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.14 - HẬU KIỂM TẤT CẢ GIAO DỊCH CHI TIẾT.
        /// </summary>
        public static string TOS_SUP_14 {
            get {
                return ResourceManager.GetString("TOS_SUP.14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.15 - HẬU KIỂM GIAO DỊCH ƯU TIÊN.
        /// </summary>
        public static string TOS_SUP_15 {
            get {
                return ResourceManager.GetString("TOS_SUP.15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.16 - HẬU KIỂM GIAO DỊCH ƯU TIÊN CHI TIẾT.
        /// </summary>
        public static string TOS_SUP_16 {
            get {
                return ResourceManager.GetString("TOS_SUP.16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.17 - HẬU KIỂM THỐNG KÊ LƯU LƯỢNG XE.
        /// </summary>
        public static string TOS_SUP_17 {
            get {
                return ResourceManager.GetString("TOS_SUP.17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.18 - HẬU KIỂM BÁO CÁO NHẬN DẠNG.
        /// </summary>
        public static string TOS_SUP_18 {
            get {
                return ResourceManager.GetString("TOS_SUP.18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.19 - DANH SÁCH ĐỐI TƯỢNG VI PHẠM.
        /// </summary>
        public static string TOS_SUP_19 {
            get {
                return ResourceManager.GetString("TOS_SUP.19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.20 - THÊM MỚI THÔNG TIN VI PHẠM.
        /// </summary>
        public static string TOS_SUP_20 {
            get {
                return ResourceManager.GetString("TOS_SUP.20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.21 - LỊCH SỬ XỬ LÝ VI PHẠM.
        /// </summary>
        public static string TOS_SUP_21 {
            get {
                return ResourceManager.GetString("TOS_SUP.21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.22 - CẬP NHẬT THÔNG TIN VI PHẠM.
        /// </summary>
        public static string TOS_SUP_22 {
            get {
                return ResourceManager.GetString("TOS_SUP.22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.23 - XÓA ĐỐI TƯỢNG VI PHẠM.
        /// </summary>
        public static string TOS_SUP_23 {
            get {
                return ResourceManager.GetString("TOS_SUP.23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.24 - GIÁM SÁT TRẠNG THÁI THIẾT BỊ.
        /// </summary>
        public static string TOS_SUP_24 {
            get {
                return ResourceManager.GetString("TOS_SUP.24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.25 - CẬP NHẬT CƠ SỞ DỮ LIỆU ĐĂNG KIỂM.
        /// </summary>
        public static string TOS_SUP_25 {
            get {
                return ResourceManager.GetString("TOS_SUP.25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOS_SUP.26 - QUẢN LÝ THẺ LƯU HÀNH.
        /// </summary>
        public static string TOS_SUP_26 {
            get {
                return ResourceManager.GetString("TOS_SUP.26", resourceCulture);
            }
        }
    }
}
